For payments initiated by payment request buttons, set form top error container
woocommerce/woocommerce-gateway-stripe pull request #1402
Opened 2020-12-08 00:03 UTC by allendav

# Changes proposed in this Pull Request:

Issue: Link to the GitHub issue this PR addresses (if appropriate).
Fixes #879 

Description: If a payment request button is used to initiate payment and fails (e.g. using a 3D Secure test card and then clicking FAIL when prompted) ensure the error is displayed to the user (and not just console logged.) To pull this off, we set a data flag on the payment request button itself when it is used to initiate payment. If an error occurs and that flag is present, it prompts us to use the woocommerce-notices-wrapper div as the error container.

Images or gifs: Include before and after screenshots or gifs/videos when it makes sense.

<img width="1046" alt="Screen Shot 2020-12-07 at 3 53 08 PM" src="https://user-images.githubusercontent.com/1595739/101419641-4b5bd180-38a5-11eb-8fb2-d64acdde159b.png">
<img width="1027" alt="Screen Shot 2020-12-07 at 3 52 32 PM" src="https://user-images.githubusercontent.com/1595739/101419644-4d259500-38a5-11eb-8b3e-bd803f99bd69.png">
<img width="1001" alt="Screen Shot 2020-12-07 at 3 51 54 PM" src="https://user-images.githubusercontent.com/1595739/101419646-4dbe2b80-38a5-11eb-8796-6f7669c18843.png">

# Testing instructions

- Install this branch and activate it
- Ensure you are set up with keys and test mode for the Stripe plugin and that payment request buttons are enabled
- Add this filter:

`add_filter( 'wc_stripe_show_payment_request_on_checkout', '__return_true' );`

- Navigate to a product page using Chrome
- Click on the payment request button. When prompted, enter the 4000 0000 0000 3063 test card
- Enter a dummy CCV when prompted (e.g. 123)
- Wait for the Authorize/Fail modal. Click Fail.
- Ensure the error message is displayed
- Repeat for cart and checkout pages

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

(remove me)
- [ ] Did I add a title? A descriptive, yet concise, title.
- [ ] How can this code break?
- [ ] What are we doing to make sure this code doesn't break?

2020-12-09 11:07 UTC, reykjalin requested changes
I'm happy with the general approach here, but this doesn't seem to be working for me.

Using the default gateway configuration for the payment request buttons and Brave nothing happens.

I think this is because the code where we [set the initiator data property](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1402/files#diff-73c011ce1388f1432621c0fb207e47201e82f70fdf7e4a9b0d44eb47a9cb515bR582-R586) is never entered with the payment request button type set to `Buy`, as seems to be the default:

![image](https://user-images.githubusercontent.com/13835680/101622033-83a01300-3a51-11eb-8312-2e52cc89c45b.png)

This is because the check used for the payment request buttons is just checking for `Custom` or `Branded`.

I assume this is supposed to work for any type of payment request button, so we probably need to address this?

I think we just set the `data` property on the button, regardless of the type of button 🤔

2020-12-09 21:05 UTC, allendav commented
@reykjalin - I didn't think to test with it set to other settings - I'll fix this asap

2020-12-09 22:13 UTC, allendav commented
@reykjalin - in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1402/commits/c48bd3a7ea7b847af8a87b721325f11f1580b04e I changed a few things. We first bind a click handler for any button type and any page. That should take care of what you're seeing. Be sure to have Disable cache (while Dev Tools is open) so you don't get old cached JS from before. I also chose to simplify the flagging. It applies a class (not a data) to the body element.

Please let me know if you have any concerns or problems with it and thanks again for your thorough testing!!!!11!!

2020-12-10 08:11 UTC, reykjalin requested changes
Works like a charm! 🥇 

I think we should just add some comments explaining why we're doing this, but otherwise we're ready to merge 👏

2020-12-10 08:11 UTC, reykjalin commented on assets/js/stripe-payment-request.js
> +			});
Similarly to my other comment, we should probably include _why_ we need to know when a PRB initiated a payment 🙂

2020-12-10 08:12 UTC, reykjalin commented
@allendav I'm labeling this as `Ready to Merge` despite requesting changes to reflect that I don't think we need another review+approval before we merge once the comments have been addressed :)

Also, the branch needs a rebase on `master` before being merged :)

2020-12-10 23:44 UTC, allendav commented
Updated comments and rebased

2020-12-11 17:56 UTC, merged