Save and clear UPE appearance
woocommerce/woocommerce-gateway-stripe pull request #1725
Opened 2021-08-20 20:35 UTC by cesarcosta99

# Changes proposed in this Pull Request:
Fixes #1709 

This PR implements a solution to store the UPE appearance values in a transient so they don't have to be calculated every time and can be used on pages where it is unable to be calculated (order pay page for example). The UPE appearance should be properly calculated, stored in a transient that expires in 24 hours or clears on theme change, and then applies the saved UPE appearance from the transient during checkout.

PS: not basing this PR from `develop` because it's broken and missing some UPE code, which do not allow me to test and rely my changes on it. So I tested on @diegocurbelo 's branch, where it should be working nicely.

# Testing instructions
Transient SQL check:
```sql
SELECT * FROM wp_options WHERE option_name = '_transient_wc_stripe_upe_appearance';
```
1. Access the database.
2. Run the transient query check and you should see no records.
3. Go to the shop page and add an item to the cart.
4. Go to the checkout page.
5. Run the transient query again and you should see one record.

-------------------
- [x] Make sure your changes respect [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] Did you make changes, or create a **new .js file**? If **Gruntfile.js** exists in the repo, make sure to run `grunt`.

2021-08-23 14:53 UTC, diegocurbelo requested changes

2021-08-23 14:53 UTC, diegocurbelo commented on includes/class-wc-stripe-intent-controller.php
> +	const UPE_APPEARANCE_TRANSIENT = 'wc_stripe_upe_appearance';
Maybe we can use `WC_Stripe_UPE_Payment_Gateway:: UPE_APPEARANCE_TRANSIENT` instead of having the same constant in each file?

2021-08-24 14:24 UTC, diegocurbelo approved these changes, later dismissed
LFTM 🚢 

We need to change the base to develop or wait for #1659 to be merged

2021-08-25 14:38 UTC, EvanDotPro approved these changes
Rebased, good to merge.

2021-08-25 14:46 UTC, merged