feat: add UPE tracking capability
woocommerce/woocommerce-gateway-stripe pull request #1859
Opened 2021-09-14 22:48 UTC by frosso

# Changes proposed in this Pull Request:

Tracking events for enabling/disabling the UPE feature.

# Testing instructions

2021-09-14 22:49 UTC, frosso commented on client/tracking/index.js
> +import domReady from '@wordpress/dom-ready';
Same as what we're doing in WCPay: https://github.com/Automattic/woocommerce-payments/blob/538b322f4576b7cb070332dc627e8a21cfab5c7a/client/tracks/index.js

2021-09-15 08:53 UTC, waclawjacek requested changes
Works exactly as described! :100: Clicking request changes because of that `console.log` comment.

BTW for testing: turn off your adblocker and the request is an image rather than a XHR request. :)

2021-09-15 08:53 UTC, waclawjacek commented on client/tracking/index.js
> +		console.log( '###', { isEnabled: isEnabled(), lib: getLibrary() } );
This line should probably go, right?

```suggestion
```

2021-09-15 13:02 UTC, frosso commented on client/tracking/index.js
> +		console.log( '###', { isEnabled: isEnabled(), lib: getLibrary() } );
🤦 how did I miss that! 😆

2021-09-15 13:36 UTC, waclawjacek approved these changes
LGTM! :shipit:

2021-09-15 15:35 UTC, merged