Update the newly created PM with the customer name and email
woocommerce/woocommerce-gateway-stripe pull request #2071
Opened 2021-10-15 01:11 UTC by diegocurbelo

# Changes proposed in this Pull Request:

Fixes #1802 

When adding a new payment method the freshly saved payment method in Stripe's dashboard does not contain the customer name nor the email (it gets however linked to the customer correctly), this PR adds a call to Stripe's `update payment method` API with the customer billing info stored in WC.

## Before
![68747470733a2f2f63646e2d7374642e64726f706c722e6e65742f66696c65732f6163635f313130343230362f767a7130764d](https://user-images.githubusercontent.com/407542/132569199-1ecac182-ee25-4082-b1ba-3a08fa4c38e0.png)

## After
<img width="1243" alt="Screen Shot 2021-10-15 at 12 14 03" src="https://user-images.githubusercontent.com/407542/137511533-87c69d23-9869-401d-afb0-a6242afff04b.png">

# Testing instructions

0. Make sure UPE is enabled (`Try the new payment experience (Early access)` is checked)
1. Go to My account -> Add payment method
2. Click on `Add payment method`
3. Fill the form with any test credit card
4. Go to the Stripe dashboard -> Customers (https://dashboard.stripe.com/test/customers)
5. Select the customer used to add the new payment method
6. Expand the newly created payment method, and check that `Name`, `Email` and `Billing address` are not empty

2021-10-18 20:51 UTC, FangedParakeet requested changes
I tested this and everything worked (mostly) just as expected! I've left a few comments--most of them aren't really critical, but if you could have a quick look at them and gimme your thoughts, that'd be grand!

I had some saved SEPA tokens when I was testing and I noticed that for some reason my store started creating duplicate tokens, which broke some of the functionality here, since when there are too many WC Payment Tokens present, we stop checking for new tokens on Stripe's side. I don't think it's related to the changes here, so I re-opened #1857 and left a comment with a better explanation of the preceding sentence [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1857#issuecomment-946147842).

Let me know what you think about my suggestions and I'll review again gladly once you're ready. Cheers!

2021-10-18 20:51 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						$customer_data = WC_Stripe_Customer::map_customer_data( null, new WC_Customer( wp_get_current_user()->ID ) );
```suggestion
						$customer_data = WC_Stripe_Customer::map_customer_data( null, $customer );
```
Can we not reuse the `$customer` instance that gets created above before the `try` block, instead of creating a new one here?

2021-10-18 20:51 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						$setup_intent = WC_Stripe_API::request( [], 'setup_intents/' . $setup_intent_id, 'GET' );
```suggestion
						$setup_intent_id = isset( $_GET['setup_intent'] ) ? wc_clean( wp_unslash( $_GET['setup_intent'] ) ) : '';
						$setup_intent    = WC_Stripe_API::request( [], 'setup_intents/' . $setup_intent_id, 'GET' );
```
My linter doesn't like the spacing and alignment here. I just want to make it clear here that my linter is making a complaint here, not me.

2021-10-18 20:51 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						);
```suggestion
						$this->stripe_request(
						    'payment_methods/' . $setup_intent->payment_method,
							[
								'billing_details' => [
									'name'    => $customer_data['name'],
									'email'   => $customer_data['email'],
									'phone'   => $customer_data['phone'],
									'address' => $customer_data['address'],
								],
							]
						);
```
I just want to point out that there is a wrapper function for static calls to the `WC_Stripe_API` class in the `WC_Stripe_UPE_Payment_Gateway` class called `stripe_request`. This is mainly here so that it can be mocked out for unit tests, but I think every other function in the UPE gateway is--for better or worse--using it. It's a contentious way to mock out Stripe API calls, since at times it makes it a little difficult to check parameters sent to the API, but I just thought I'd mention it for consistency's sake. 

In this case, it's probably particularly unhelpful to use, because there isn't really a lot we can test here. We would probably like to test the parameters of each function call, but I found out the hard way that confirming that a function called twice has different parameters each time is apparently not as easy as one might think it would be to do.

Anyways, I wasn't sure if you were aware this function existed, so I just thought I'd mention it to see if it stirs up any deep passions within you.

2021-10-18 20:51 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +					} catch ( Exception $e ) {
```suggestion
                         do_action( 'woocommerce_stripe_add_payment_method', $user->get_id(), $setup_intent->payment_method );
					} catch ( Exception $e ) {
```
When we add new payment methods during checkout [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L848), we call the `woocommerce_stripe_add_payment_method` hook: should we be doing the same thing here as well? If you decide to do so, you may have to do a little more work, since that final hook parameter is expecting a payment method object; you could expand the `payment_method` field in the request to `/setup_intents/seti_...`, for example...Just food for thought.

2021-10-18 20:51 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
```suggestion
					} catch ( WC_Stripe_Exception $e ) {
						WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
						wc_add_notice( $e->getLocalizedMessage(), 'error', [ 'icon' => 'error' ] );
```
This is a minor one, but looks like `WC_Stripe_Customer` and `WC_Stripe_API` both only throw `WC_Stripe_Exception`: we could take advantage of this to throw a nice localised error notice here (or we could not, up to you).

2021-10-20 17:41 UTC, diegocurbelo commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						$customer_data = WC_Stripe_Customer::map_customer_data( null, new WC_Customer( wp_get_current_user()->ID ) );
We can't use `$customer` because `map_customer_data(...)` expects a `WC_Customer` and not a `WC_Stripe_Customer` as the second param.

Despite what the name may suggest, `WC_Stripe_Customer` does not extend `WC_Customer` 😞

2021-10-20 17:48 UTC, diegocurbelo commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						);
I didn't know about that function... its true that there is not much to test other than the API call, but it makes sense to always use the wrapper

2021-10-20 19:14 UTC, diegocurbelo commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
I agree with the change to `WC_Stripe_Exception`, but not with adding an error notice... the payment method was added and it will be shown after the page reloads, I think that displaying an error notice to the customer would be confusing.

Also, the missing Stripe info will be filled/updated when the customer makes a payment.

2021-10-20 19:22 UTC, diegocurbelo commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +					} catch ( Exception $e ) {
We can use the response from the `payment_methods/<pm_id>` POST that contains the full payment method object as the hook's final param.

But I'm not sure if we should do this here or if it would be better to add the call when we sync any new payment method from Stripe (when listing the payment methods)...
If we do it here, we need to add some sort of retry to the API call or risk the hook not being called (or called without the payment method object), so maybe the other alternative is the best, what do your think @FangedParakeet?

2021-10-20 21:23 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						$customer_data = WC_Stripe_Customer::map_customer_data( null, new WC_Customer( wp_get_current_user()->ID ) );
Whoops, you're totally right, I misread that! Ignore my suggestion in that case.

2021-10-20 21:27 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +						WC_Stripe_Logger::log( 'Error: ' . $e->getMessage() );
Cool, that makes sense. I was thinking of mirroring the notice that is displayed in the error `else` block, but agree catching any exception thrown in the opposite block is already in a successful state and consequently redundant. Considering this further, I think the only exceptions thrown are likely to be due to network errors during API requests and in those scenarios we will probably be unable to add the payment method in the first place, so won't even get that far.

2021-10-20 23:05 UTC, FangedParakeet commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +					} catch ( Exception $e ) {
I'm honestly not sure of how this `woocommerce_stripe_add_payment_method` is currently being used by any other plugins, but it makes sense to me to fire the action when the payment method is actually added, rather than when we actually create the WC Payment Token. Our current implementation takes advantage of how we meticulously check Stripe for new payment methods to allow us to resist having to create a new payment token when we save the payment method, but I don't think it's obvous to any end-user that would like to hook into this action that this is how things work--it wasn't obvious to me and I wrote half of that code!

So yeah, I would argue that we should fire the action when we actually add the payment method on Stripe's side, which is also a bit closer to what the hook name `woocommerce_stripe_add_payment_method` suggests it might do. Please let me know if we actually have these hooks documented somewhere and are saying otherwise though!

With that being my vantage point, I'd say that we should fire the action here or [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/class-wc-stripe-intent-controller.php#L472-L502), where we create the setup intent. It seems like it would be easier to do it here, since we are making the `POST` to `payment_methods/<pm_id>`, so, as you stated, we do have the payment method object at our disposal. Will we need to add a retry to the API? If the `POST` request succeeds, Stripe guarantees us that it will return the payment method object; if not, I think we can be fairly confident that something has gone awry with saving the payment method. Perhaps you could argue that we'd be more confident of the payment method having been saved when we create the setup intent, but we'd have to make another request or expand the payment method in order to have access to it at that point. 

I think we can safely drop the hook here, but if you think otherwise, I'm happy to yield to your better judgement.

2021-10-21 21:25 UTC, diegocurbelo commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +					} catch ( Exception $e ) {
I agree, you have a really good point... I added the call to the action hook here 👍🏼

2021-10-21 22:04 UTC, FangedParakeet approved these changes
Thanks for responding to all my goofy feedback! This looks solid to me and is working just as expected: adding new payment methods stores the complete user information on the generated Stripe payment method. 

LGTM, let her loose!

2021-10-22 14:46 UTC, merged