Add stripe link headers to requests
woocommerce/woocommerce-gateway-stripe pull request #2375
Opened 2022-06-30 13:03 UTC by dpaun1985

Fixes #2366 

## Changes proposed in this Pull Request:
When Stripe Link is enabled, the requests to Stripe should have `link_autofill_modal_beta_1` and `link_beta_2` headers. Also api version should be `2020-08-27;link_beta=v1`.

## Testing instructions
- all tests should pass. 
- create orders with and without UPE enabled. We should not encounter any errors.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2022-06-30 22:10 UTC, ricardo requested changes
Looking good.

UPE still works for me after the change.

2022-06-30 22:10 UTC, ricardo commented on client/api/index.js
> +		const { key, locale, isUPEEnabled, paymentMethodsConfig } = this.options;
You probably already noticed, but the linter suggests breaking this into multiple lines.

2022-06-30 22:10 UTC, ricardo commented on client/api/index.js
> +			undefined !== paymentMethodsConfig.link;
Does `card` need to be enabled for `link` to be enabled, or can it work separately, like other UPE payment methods?

2022-06-30 22:10 UTC, ricardo commented on client/api/index.js
> +				}
We already have a check `if ( isUPEEnabled )` right above, so no need for this second `if`.

We can do `let betas = [ 'payment_element_beta_1' ];`.

2022-06-30 22:10 UTC, ricardo commented on client/api/index.js
> +		}
This if is redundant as `if ( [] )` should validate as `true`, so we can either do `if ( betas.length )` or if it doesn't matter to have an empty array, `const options = { locale, betas };`.

2022-06-30 22:10 UTC, ricardo commented on client/api/index.js
> +			options.apiVersion = '2020-08-27;link_beta=v1';
Just as a side note, no need to change anything now, but maybe we will need to change the [back-end Stripe API version](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/db315182e581a89b5a177c4d485c39f6cf8b77f6/includes/class-wc-stripe-api.php#L17) as well? 🤔

2022-07-01 06:39 UTC, dpaun1985 commented on client/api/index.js
> +			undefined !== paymentMethodsConfig.link;
`link` can work only with `card` payment method. So yes, we need both payment methods enabled.

2022-07-01 06:57 UTC, dpaun1985 commented on client/api/index.js
> +			options.apiVersion = '2020-08-27;link_beta=v1';
I expect that we don't need the new api version in backend, but if we will need it, I will change it at that time.

2022-07-01 10:44 UTC, dpaun1985 commented
> Looking good.
> 
> UPE still works for me after the change.

Thank you @ricardo !
I made the required changes. Could you please check again the PR ?

2022-07-04 17:26 UTC, ricardo approved these changes
LGTM 👍

2022-07-04 20:55 UTC, mordeth approved these changes
LGTM! ✅

2022-07-06 08:47 UTC, merged