Update product page PRB when options change
woocommerce/woocommerce-gateway-stripe pull request #2422
Opened 2022-09-01 13:28 UTC by EvanDotPro

Fixes #2322 (at least for the official Product Add-Ons extension)

This fix triggers the same PRB update routine when Product Add-On
selections change that currently runs when the quantity is changed on
the product page.

## Testing instructions

- Follow the steps to reproduce the issue in #2322.
- Checkout this branch.
- Try the steps again and verify that the correct price is shown in the Google Pay or Apple Pay pop-up when a product add-on is chosen.

---

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2022-09-23 16:06 UTC, rafaelzaleski requested changes
It's triggering an update of the PRB, but it's delayed. 

**Tests:**
1. Added text on the add-on field
2. Clicked on the PRB
**Result**: The add-on price was not included in the PR.
3. Removed the text from the add-on field
4. Clicked outside the field
5. Clicked in the PRB
**Result**: The add-on price was included in the PR.

I was checking the `product add-ons` plugin, and it seems they have a custom event we can hook into, `'woocommerce-product-addons-update'`.
`/woocommerce-product-addons/assets/js/addons.js:200` on plugin version `5.0.0`. 

It's the same event they use to update the subtotal table, so I think it's more reliable.

2022-09-29 17:25 UTC, EvanDotPro commented
@rafaelzaleski did you experience any issues with the delay you mentioned? It appears to me that the 250ms delay was put there [for a reason regarding Apple Pay](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/985) ([pr[(https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1192)), so I'm unsure if triggering the update immediately using the `woocommerce-product-addons-update` event will cause issues with Apple Pay (which I don't have an Apple device to test on).

2023-03-16 04:54 UTC, diegocurbelo approved these changes
LGTM 🚢

2023-03-16 13:53 UTC, rafaelzaleski approved these changes

2023-03-16 13:54 UTC, merged