Source User from order when anonymous, on order-pay page (Fixes #1505)
woocommerce/woocommerce-gateway-stripe pull request #2587
Opened 2023-03-30 10:22 UTC by nicomollet

Fixes #1505 

## Changes proposed in this Pull Request:

We noticed Stripe customers are duplicated in some scenarios.
Using the "Pay for Order" (order-pay) page, our users can access the page while anonymous.
When anonymous on this page, the plugin can't find the user since it only checks `get_current_user_id()` and then it creates another customer.

Proposal is: on order-pay only, if user is anonymous only, get the user from the order (`$order->get_user_id()`). It will avoid duplicating customers in Stripe.

## Testing instructions

1. Create a manual order in the backend
2. Select a customer that already paid with Stripe in the past, and add a product
3. Save the order
4. Send the link of the "Customer payment page" (looks like https://sitename/order/order-pay/ORDERID/?pay_for_order=true&key=wc_order_xxxxxxxx) to the customer
5. Customer accesses this page **anonymously** (not logged-in / private navigation)
6. Customer types a credit card in the Stripe Form and submit, payment is a success (Stripe test mode enabled)
7. In Stripe Dashboard (Payments page) you will see a new payment with a newly created customer called `Name: , Guest`. **With the fix, the customer will be the same as the user from the order. No new Customer is created **

---

-   [x ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2023-03-30 11:32 UTC, GeekPress requested changes

2023-03-30 11:32 UTC, GeekPress commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === get_current_user_id() && is_wc_endpoint_url( 'order-pay' ) ) {
`$user_id` can be reused instead of recalling `get_current_user_id()`.

2023-03-30 11:40 UTC, nicomollet commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === get_current_user_id() && is_wc_endpoint_url( 'order-pay' ) ) {
Done

2023-06-15 09:03 UTC, GeekPress approved these changes

2025-01-15 17:17 UTC, wjrosa commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Maybe `! $user_id` might be a bit easier to read/understand.

2025-01-15 19:54 UTC, nicomollet commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Thanks I edited the branch.
Are we good to go like this?

2025-01-15 20:56 UTC, wjrosa commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Code-side, yes, but I tested your change, and it is not working as expected for me 🤔 . I have to login anyway when accessing the store using an anonymous window. Maybe some of the latest updates broke it? I wanted to test a concern @diegocurbelo raised about using someone else's saved payment method.

2025-01-16 10:04 UTC, nicomollet commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
@wjrosa You got the `form-verify-email` on `order-pay` page because you accessed it after the _grace period_.
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Utilities/Users.php#L67
During the default 10 minutes grace period (has a filter), this `order-pay` page can be accessed while anonymous.

So this PR covers only the grace period. I understand that once logged in, it has no effect.

2025-01-20 18:56 UTC, wjrosa commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Not really the case. I tried to access it immediately (I just tried again). I am getting inside this condition (`order_pay` method from the `WC_Shortcode_Checkout` class, [base WC plugin](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php#L81)):
```php
				// Logged out customer does not have permission to pay for this order.
				if ( ! current_user_can( 'pay_for_order', $order_id ) && ! is_user_logged_in() ) {
					wc_print_notice( esc_html__( 'Please log in to your account below to continue to the payment form.', 'woocommerce' ), 'notice' );
					woocommerce_login_form(
						array(
							'redirect' => $order->get_checkout_payment_url(),
						)
					);
					return;
				}
```
Maybe you can bypass this check by adding a `user_has_cap` filter.

2025-01-20 19:56 UTC, nicomollet commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Yes it looks like I am using a filter on `user_has_cap` with `pay_for_order` cap. This kind of filter:
https://wordpress.org/support/topic/order-pay-without-login/

The goal is to send emails to that order-pay page for orders where payment failed (in the background, like a subscription renewal for example). And avoid form-login that reduce conversion you know.

So this might be an edge-case, but we are getting Stripe duplicate customers because of this. What do you think?

2025-01-20 20:19 UTC, wjrosa commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Hum, since this is an edge case and depends on another extension, I think the best move here is to introduce a new hook (filter/action) on this part of the code. This way you can add the specific logic there.

2025-01-20 20:35 UTC, nicomollet commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
I am good with that. Do you have a place where the filter can go? Should I suggest? Thanks

2025-01-21 12:26 UTC, wjrosa commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
I would place it in the same block you updated on this PR. You can create a filter to potentially overwrite `$prepared_source` (something like `wc_stripe_process_payment_prepared_source`). But feel free to suggest anything different from this.

2025-01-22 08:34 UTC, nicomollet commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
@wjrosa I added the filter for the user, not for the source itself.
See latest commit.
If `prepare_source` is executed, it will create another Stripe user and that's actually what I don't want (duplicates).
That's why the filter is to pass the correct `user_id` to the method. Also adds `$order` param to the filter.

2025-01-22 11:44 UTC, wjrosa commented on includes/class-wc-gateway-stripe.php
> +				if ( 0 === $user_id && is_wc_endpoint_url( 'order-pay' ) ) {
Looking good! Thanks for the update 👍

2025-01-22 11:50 UTC, wjrosa approved these changes
Thank you for the contribution and or the latest changes! It looks good to me 👍

2025-01-22 12:05 UTC, merged