Adds support to UPE on E2E tests
woocommerce/woocommerce-gateway-stripe pull request #2588
Opened 2023-04-04 20:24 UTC by rafaelzaleski

Fixes #

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2023-04-05 21:10 UTC, rafaelzaleski commented
Blocked until we fix the workflows https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2591

2023-04-10 18:25 UTC, cesarcosta99 requested changes
Code looks good.

With regards to testing, with UPE disabled, all tests passed. However, after I enabled UPE, an e2e test started failing consistently because of a timeout: "a card with invalid number shows the correct error message". See images below.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/10233985/230966480-90fab4b4-d6b6-4a41-a513-db3309086307.png">

![image](https://user-images.githubusercontent.com/10233985/230966660-98636cdf-9387-4186-81ee-83fece0ea7ee.png)

2023-04-10 18:25 UTC, cesarcosta99 commented on tests/e2e/utils/playwright-setup.js
> +		'wp plugin install disable-emails --activate',
This was a good idea 💯 I'd just add a comment saying what's the purpose of this installation to avoid someone removing it in the future.

2023-04-18 22:40 UTC, cesarcosta99 approved these changes
Code looks good and tests pass 💯 Thanks for addressing the changes.

I left a minor comment that doesn't block the merge, so feel free to ignore it.

2023-04-18 22:43 UTC, cesarcosta99 commented on tests/e2e/tests/woocommerce-blocks/card-failures.spec.js
> +	}
Nitpick: I think we could pull off the logic that's within the `soft` function into a variable before the `expect`. That would make the logic shorter and avoid code duplication. Like below:

```js
let expected;
if ( isUpe && cardKey === 'cards.declined-incorrect' ) {
	expected = await page
		.frameLocator(
			'.wc-block-gateway-container iframe[name^="__privateStripeFrame"]'
		)
		.locator( '#Field-numberError' )
		.innerText();
} else {
	expected = await page.innerText(
		cardKey === 'cards.declined-incorrect'
			? '.wc-card-number-element .wc-block-components-validation-error'
			: '.wc-block-checkout__payment-method .woocommerce-error'
	);
expect.soft( expected ).toMatch( new RegExp( `(?:${ card.error.join( '|' ) })`, 'i' ) );
```

2023-04-20 13:07 UTC, merged