Add check to see if parent order exists
woocommerce/woocommerce-gateway-stripe pull request #2597
Opened 2023-04-14 15:41 UTC by rafaelzaleski

Fixes #

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2023-04-14 17:52 UTC, rafaelzaleski commented
@reykjalin do you foresee any other issues for when a subscription doesn't have a parent order?

2023-04-14 20:09 UTC, reykjalin commented
@rafaelzaleski I'll test this later today, but from just reading the code I'd worry that the mandate isn't available in some cases where it's needed? I'll run through some testing later and see what I can find out 👍

2023-04-16 22:28 UTC, reykjalin commented
Yeah I found that the mandate isn't added when I did the following:

1. Create new subscription.
2. Add a customer to the subscription.
3. Add subscription valued at 15,000 INR or more to the subscription.
4. Choose `Manual renewal` for payment method.
5. Set subscription status to `Active`.
6. Click **Update** to create the subscription.
7. Follow the link in the subscription details to go to the customer's add payment method page and add a payment method there.
8. Go back to subscription details, select **Process renewal** from the available actions, and trigger that action by clicking the `>` button.
9. Look in my Stripe dashboard to see there is no mandate information passed on the payment intent request and no mandate is returned.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/13835680/232346089-3246710e-0e2b-4e4c-9273-93d2e68a5dd7.png">

Renewal payments work when following the eMandate testing flows from the 7.3.0 instructions, but **that's only because they're not sent through the mandate flow on Stripe's systems**.

I'm going to see if I can figure out a simple way to fix that and report back 👍

2023-04-16 22:36 UTC, reykjalin commented
I've figured out that the `wcs_get_subscriptions_for_order` call fails here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/c62fdcffaed010f065b3084ffb96c44bd021a7a1/includes/compat/trait-wc-stripe-subscriptions.php#L583

causing the function to return before adding the necessary information to generate a mandate:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/c62fdcffaed010f065b3084ffb96c44bd021a7a1/includes/compat/trait-wc-stripe-subscriptions.php#L583-L588

I'm a bit surprised to see this so I'm digging into why the subscription isn't detected.

2023-04-16 22:56 UTC, reykjalin commented
The following diff adds the right mandate options to the intent request but we don't get a mandate back for some reason 🤔 

```diff
diff --git a/includes/compat/trait-wc-stripe-subscriptions.php b/includes/compat/trait-wc-stripe-subscriptions.php
index b36ffdf5..062c9c75 100644
--- a/includes/compat/trait-wc-stripe-subscriptions.php
+++ b/includes/compat/trait-wc-stripe-subscriptions.php
@@ -563,8 +563,9 @@ trait WC_Stripe_Subscriptions_Trait {
 			return $request;
 		}
 
+		// Check parent order for mandate ID.
 		$renewals = wcs_get_subscriptions_for_renewal_order( $order );
-		if ( 1 === count( $renewals ) ) {
+		if ( 0 < count( $renewals ) ) {
 			$renewal_order   = reset( $renewals );
 			$parent_order_id = $renewal_order->get_parent_id();
 			$parent_order    = wc_get_order( $parent_order_id );
@@ -580,7 +581,15 @@ trait WC_Stripe_Subscriptions_Trait {
 
 		// Otherwise add the parameters required to create a mandate.
 
-		$subscriptions = wcs_get_subscriptions_for_order( $order );
+		// Get subscriptions for the order.
+		$subscriptions = [];
+		if ( wcs_order_contains_renewal( $order ) ) {
+			// Use the subscriptions we retrieved while checking for a parent order if this is a
+			// renewal order.
+			$subscriptions = $renewals;
+		} else {
+			$subscriptions = wcs_get_subscriptions_for_order( $order );
+		}
 
 		// If there are no subscriptions we just return since mandates aren't required.
 		if ( 0 === count( $subscriptions ) ) {
```

Not sure why, we may have to ask Stripe why that happens.

I've noticed that I don't get a 3DS pop-up when adding a the payment method after going to the `Customer add payment method page`, maybe that has something to do with it? Maybe the payment method doesn't need a new mandate? Not sure what's going on there.

2023-04-16 23:18 UTC, reykjalin commented
My diff above also doesn't fix the issue even if the customer comes back on-session to trigger 3DS and the mandate flow **because the renewal processing function won't be able to find the generated mandate**.

I think we need to do more to find the mandate ID, e.g. by looking up the first subscription payment if there is no parent order and get the mandate from there instead 🤔 

I'll stop digging at this point and let you continue working on the fix @rafaelzaleski. Happy to pair up on getting this working properly if you'd like 👍

2023-04-16 23:20 UTC, reykjalin requested changes
See previous comments, doing this for the formality of it 👍

2023-04-18 19:32 UTC, reykjalin approved these changes
As discussed in the team chat I'm approving this because it fixes the problem and we're going to create a follow-up issue to fix the problems this creates with eMandates.

2023-04-18 19:34 UTC, merged

2023-04-24 10:13 UTC, EjayhanFernandes commented
37872140-hc - Rolling back to 7.2.0 fixed the issue for now.