Show Stripe Link button only if link is enabled in the settings
woocommerce/woocommerce-gateway-stripe pull request #2628
Opened 2023-06-01 03:38 UTC by Mayisha

Fixes #2479 

## Changes proposed in this Pull Request:
The Link payment request button is showing up in the cart/checkout page irrespective of the settings in the **Stripe -> Express Checkout** section. To prevent this from appearing merchants has to either disable Google/Apple Pay from the **Stripe -> Express Checkout** section or disable the Link from Stripe itself.

The reason behind this issue is when the payment request (Google/Apple) is enabled in **Stripe -> Express Checkout** settings and we check the `canMakePayment` ability in `assets/js/stripe-payment-request.js` from Stripe, it returns the status for all the types (Google Pay, Apple Pay, Link). On an incognito browser or on a browser where Google Pay or Apple Pay is not available, as the fallback it renders the next enabled method (which is Link here) if the Link payment request button is enabled in the Stripe settings.

### How to reproduce the issue
- Test on `develop` branch.
- Enable Link in payment request button on your Stripe dashboard (https://dashboard.stripe.com/settings/link)
- Go to **Stripe -> Express Checkout** settings.
- Enable Google/Apple Pay and disable Link.
- Open the browser in incognito mode (to ensure that Google/Apple Pay is not available) and add a product to the cart.
- Go to the cart page and find the `Pay with Link` button.

<img src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/33387139/4b2a6607-c3ab-46cc-ab82-3015003e0ef2" width="50%" height="50%" />

### Testing instructions
- Test on this branch.
- Enable Link in payment request button on your Stripe dashboard (https://dashboard.stripe.com/settings/link)
- Go to **Stripe -> Express Checkout** settings
- Enable Google/Apple Pay and disable Link.
- Open the browser in incognito mode (to ensure that Google/Apple Pay is not available) and add a product to the cart.
- Go to the cart page and ensure the `Pay with Link` button is not there.
- Now enable Link in **Stripe -> Express Checkout** settings.
- Reload the previous cart page incognito and ensure that the `Pay with Link` button is present.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2023-06-06 16:30 UTC, a-danae requested changes
Hey, thanks for addressing this Mayisha!

Looking good! The issue seems to be solved, but the behavior of other PRBs changed a bit. I've left a comment below with the details. That behavior should stay the same as it was, right?

Besides that, just a heads up not to forget the changelog entry for this change 🙂 Thanks again!

2023-06-06 16:30 UTC, a-danae commented on assets/js/stripe-payment-request.js
> +					if ( result.link && ! wc_stripe_payment_request_params.stripe.allow_link ) {
The reported issue doesn't happen anymore with these changes 🎉 but the behavior changed when other payment request types are enabled. Steps:

1. Set up Google Pay in Chrome (or Apple Pay in Safari)
2. As a merchant, enable Google Pay and Apple Pay and disable Link
3. As a shopper, visit the checkout page in a browser where Google Pay or Apple Pay would show up
4. Notice that the Google Pay/Apple Pay button doesn't show up
5. Checkout `develop`, build the scripts, and reload the checkout page
6. Notice that the Google Pay/Apple Pay button shows up

<img width="1590" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/07436f09-65cc-4298-95c1-6c6b1fd4cc60">

Maybe we should bail only if other payment request types aren't available?

2023-06-07 10:15 UTC, Mayisha commented on assets/js/stripe-payment-request.js
> +					if ( result.link && ! wc_stripe_payment_request_params.stripe.allow_link ) {
Good catch @a-danae :face_with_head_bandage: 
Fixed this in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2628/commits/436da3e1f6efa0d6216481a019cb5500dc518e59 and now checking for other enabled types before the early return.

2023-06-08 18:48 UTC, a-danae approved these changes
Looks good and the code makes sense to me. Thanks for the adjustments @Mayisha !

2023-06-13 04:37 UTC, merged

2025-02-01 07:38 UTC, cremigerhonig commented
its still an issue in Germany. please see here

![Image](https://github.com/user-attachments/assets/7f4eda0d-d4e6-4e36-a035-f15838a46567)
also here

![Image](https://github.com/user-attachments/assets/716f7110-f9cb-4a94-8601-423c44e2cb39)

I try to remove it using CSS like this

```
.p-LinkAutofillPrompt {
  display: none!important;
}
```

and

```
.AnimateSinglePresenceItem.p-LinkAutofillPrompt-animationItem {
  display: none;
}
```

no changes

I also turn of under 

https://dashboard.stripe.com/settings/link
no changes
I also try to turn of under
https://dashboard.stripe.com/settings/payment_methods

but stripe keeps telling me that woocomerce (the payment plugin) is handling the payments so I cant do anything..

what to do?

this is also mentioned here

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2479

2025-02-01 08:53 UTC, cremigerhonig commented
I just noticed 

when I have stripe gateway as second payment option while using the customizer to block css

```
.p-LinkAutofillPrompt {
  display: none!important;
}
```
then the link text is not display

the reason is that stripe is loading the link text with a little delay. try it yourself