Add/update customer address details when processing payments and include shipping details on each payment_intent request
woocommerce/woocommerce-gateway-stripe pull request #2731
Opened 2023-10-26 06:28 UTC by mattallan

Fixes #1206 

## Changes proposed in this Pull Request:

In order for our Stripe plugin to support merchants in India, each international payment for physical goods is required to have the buyer's name, billing address, description, and shipping address.

Taken from [Stripe's documentation](https://stripe.com/docs/india-accept-international-payments#international-payments-for-goods), here are the requirements:

1. Each Payment Intents API request must include the description and a shipping address
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/713217fb-8239-430e-a6e9-1038f6650d03)
2. Customers must have a name and billing address
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/cfbe847c-6555-4927-8413-dacb25191984)

To meet these requirements this PR has made the following changes:
- b313a96afbe83e505419732acfa1494263d239e8 In this commit I've updated the `generate_customer_request()` to populate the user's billing address. With this change, each time we call `WC_Stripe_Customer::create_customer()` or `update_customer()` we will be attaching the billing address details and updating them if they've changed. This should satisfy the 2. requirement above.
- ca699a0e9b4c168f947b64d40ae0b40d45b455b9 Makes sure we add the customers shipping address details to all of our `/payment_intent` requests. Most of our payment intent requests already did the ([here's one example](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/6913216206983ff001831ba2ab2a038de43283a5/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1743-L1745)) however I found a couple of instances where the shipping details weren't being sent.

## Testing instructions

There are a lot of potential cases to test here i.e.
- Different Stripe payment methods
- PE (New Checkout Experience) & non-PE
- Guest customers & existing customers
- Saved cards & new cards
- Subscriptions & simple products

Rather than listing off instructions for all cases here's a general list of instructions I followed:
1. If testing with an existing customer, go to https://dashboard.stripe.com/test/customers/ and delete the customer in Stripe
2. In `wp_usermeta` table delete the row `wp__stripe_customer_id` for the user ID you're going to test with
3. Purchase a product on the checkout using a saved or new card
4. Refresh the https://dashboard.stripe.com/test/customers and view the new customer in Stripe

|On `develop`|On this branch|
|:----------:|:------------:|
|![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/b1aab327-b8cd-4c67-840b-4d08ce6d1c57)|![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/40c6b4e3-7f66-41ea-802a-536bdee63202)|

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2023-10-27 22:38 UTC, diegocurbelo requested changes
Code changes look good (UPE version is consistent with the classic implementation), and it tests well, but... two tests are now failing, for the UPE `process_payment` flow.

There is no equivalent test for the non UPE flow, likely because we are instantiating a new `WC_Stripe_Customer` and that class uses the static `WC_Stripe_API::request` that we would need to mock to fix the errors.

@mattallan I'm a bit hesitant about doing a major refactor to make this testable right when we are about to change it to deferred/split PE; what do you think? 🤷🏼

2023-10-30 07:19 UTC, mattallan commented
Thanks @diegocurbelo for giving this PR a review!

> I'm a bit hesitant about doing a major refactor to make this testable right when we are about to change it to deferred/split PE; what do you think?

I agree! In order to avoid a huge set of changes I just pushed up a relatively small change that allows us to get the unit tests working again (see [b0be09a](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2731/commits/b0be09a12084ab30dea0be043c0c343c9e0ea393)). The solution was to move the `new WC_Stripe_Customer()` into a separate function so that we can then mock it inside the unit tests.

Let me know your thoughts on this.
It seems a bit odd to do this but I wasn't sure of an alternative 😅

2023-10-30 21:24 UTC, diegocurbelo commented
> Let me know your thoughts on this. It seems a bit odd to do this but I wasn't sure of an alternative 😅

I like the solution, the impact is limited to the new code 👍🏼

2023-11-02 03:39 UTC, diegocurbelo approved these changes

2023-11-02 04:25 UTC, mattallan commented
Thanks @diegocurbelo for approving this 😄 I just fixed a typo in the changelog but I also noticed I didn't copy the correct changelog entry in my other PR into readme.txt so I just patched that up here as as well.

I'll merge this once the checks pass

2023-11-02 04:45 UTC, merged

2023-12-14 19:13 UTC, SumayInfotech commented
Still facing this issue in updated plugin version.
Can we get it resolved?

2023-12-14 23:12 UTC, mattallan commented
Hey @SumayInfotech thanks for the message.

Just to clarify, this PR will only add/update customer address details when processing a payment for that customer, and it will not fix all existing customers that have missing details until we process a payment for them.

Can you confirm this issue still exists for new purchases?
Thanks!