[Deferred intent] Allow saving cards and using saved ones
woocommerce/woocommerce-gateway-stripe pull request #2816
Opened 2023-12-30 18:55 UTC by a-danae

Fixes #2760

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-01-10 05:07 UTC, james-allan requested changes
Changes look pretty good @a-danae! 

I went through the following testing instructions and ran into some issues using a saved payment method on the classic checkout. Details below. 

- [x] **Disabled the save payment method setting ([screenshot](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/dc8daa18-d1de-465c-baad-a293c8ea27ad)).**
   - On checkout. No checkbox to save. 👍 
   - A purchase using a card didn't save the method in Stripe or WC. 👍 
   - No setup intent. 👍 
- [x] **Saving payment methods enabled ([screenshot](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/3fa0ffb7-26a1-49cf-9ab2-cd553e2dc46d)).**
- 🔲 **Block Checkout** 🔲
   - [x] Choosing **_not_** to save. ie leave the checkbox unchecked on checkout.
      - A purchase using a card didn't save the method in Stripe or WC. 👍 
      - No setup intent. 👍 
   - [x] Saving a **_standard_** card (Mastercard).
      - Saved in Stripe. 👍 
      - Saved in WC. 👍
      - Set up intent. 👍 ([screenshot](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/047573a7-1971-42ac-a6ed-4015a62b9699))
   - [x] Saving a **_3DS_** card. 
      - Saved in Stripe. 👍 
      - Saved in WC. 👍 
      - Set up intent. 👍 
   - [x] Using a saved **_standard_** card (Mastercard). 
      - PI saved in order meta. 👍 
      - Saved PM is used to process the payment. 👍 
      - Saved PM saved in order meta. 👍
   - [x] Using a saved **_3DS_** card.
      - Re-authed 👍 
      - PI saved in order meta. 👍 
      - Saved PM is used to process the payment. 👍 
      - Saved PM saved in order meta. 👍
- 🏛️ **Shortcode/Classic Checkout** 🏛️
   - [x] Choosing **_not_** to save. ie leave the checkbox unchecked on checkout.
      - A purchase using a card didn't save the method in Stripe or WC. 
      - No setup intent. 
   - [x] Saving a **_standard_** card (AMEX).
      - Saved in Stripe. 👍
      - Saved in WC. 👍
      - Set up intent. 👍
   - [x] Saving a **_3DS_** card. 
      - Saved in Stripe. 👍 
      - Saved in WC. 👍 
      - Set up intent. 👍
   - [x] ❌ Using a saved **_standard_** card (AMEX). 
   - [x] ❌ Using a saved **_3DS_** card.

@a-danae when I try to use a saved payment method on the classic/shortcode checkout, I get the following error: 

<img width="1193" alt="Screenshot 2024-01-10 at 3 03 57 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/ba9d7347-caf5-4b21-94f7-34daf982ff51">

Do you get the same error message?

2024-01-10 05:07 UTC, james-allan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +	 * @param WC_Order $order The WC order for which we're getting the statement descriptor.
```suggestion
	 * @param WC_Order $order The WC order for which we're getting the statement descriptor.
	 * @param string $selected_payment_type The selected payment type.
```

The order of these params don't match the function signature. `$order` is the first param.

2024-01-10 10:55 UTC, a-danae commented
Thanks for the thorough testing, @james-allan !

> when I try to use a saved payment method on the classic/shortcode checkout, I get the following error:

Interesting... This validation shouldn't be triggered when using a saved payment method. 
I'm not able to replicate this on my end. I tested in both the classic checkout added via shortcode and via blocks.

Mind sharing the ID and name of this input on your end?
<img width="400" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/c71ec283-c9a1-4183-897a-151311e6a41c">

My thoughts:
- The "Your card number is incomplete" error is triggered by the Payment Element in the frontend. It's triggered in [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/save-cards-deferred-intent/client/classic/upe/payment-processing.js#L275). 
- But the parent processPayment() function that triggers this validation shouldn't be called when using a saved card. It should [only be called](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/save-cards-deferred-intent/client/classic/upe/deferred-intent.js#L41) on the checkout page when **not** using a saved payment method. 
- To define whether we're using a saved payment method, we check this input by its ID [over here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/save-cards-deferred-intent/client/stripe-utils/utils.js#L285-L295). I'm thinking this check is failing. Maybe the ID is different in a scenario I missed.

2024-01-17 17:43 UTC, a-danae commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +	 * @param WC_Order $order The WC order for which we're getting the statement descriptor.
Good catch. It's updated now, thanks!

2024-01-18 00:13 UTC, james-allan commented
> Mind sharing the ID and name of this input on your end?

Looks like its the same ID:
<img width="1522" alt="Screenshot 2024-01-18 at 10 02 30 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/02d6e196-c4a3-402b-9653-2c703404ae3b">

I can still replicate it today so I'll take a look on my end and see if I can narrow it down.

2024-01-18 00:22 UTC, james-allan commented
So it looks like the flow that leads to this error is starting in the [`processPaymentIfNotUsingSavedMethod()` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/save-cards-deferred-intent/client/classic/upe/deferred-intent.js#L38-L43). It uses the stripe utils version of the `isUsingSavedPaymentMethod()` function which has slightly different element IDs. 

ie it looks for `'#wc-stripe-new-payment-method'` rather than `#wc-stripe-payment-token-new`. Here's a link to that function: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/save-cards-deferred-intent/client/stripe-utils/utils.js#L290-L295.

2024-01-18 02:40 UTC, james-allan commented
> So it looks like the flow that leads to this error is starting in the [processPaymentIfNotUsingSavedMethod() function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/save-cards-deferred-intent/client/classic/upe/deferred-intent.js#L38-L43). It uses the stripe utils version of the isUsingSavedPaymentMethod() function which has slightly different element IDs.

🤦‍♂️🤦‍♂️🤦‍♂️ so sorry @a-danae. I somehow had an old version of the Stipe Utils JS file and just noticed you have updated that function in this PR. After force updating my local branch with the latest version of this branch, it works now. 😅

2024-01-18 03:05 UTC, james-allan approved these changes

2024-01-18 05:24 UTC, mattallan commented
Hey @a-danae 👋 I just merged my Split-PE PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2827 and resolved the conflicts that were in this PR, but when I tried to test saving cards and using saved cards in a split PE environment i got the following results:

- ✅ Saving a new card.
- :x: Using an existing saved card seems to be broken in a Split PE environment.

Here's the error I'm getting:

![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/714bce78-b9c2-4685-95df-d9aaf00256d8)

After doing some digging, the issue is caused by this line in the `prepare_payment_information_from_request()` function:

```
$selected_payment_type = sanitize_text_field( wp_unslash( $_POST['wc_stripe_selected_upe_payment_type'] ?? '' ) );
```

Previously with the old Stripe UPE we were hooking onto the StripeElements.change event and setting the selected payment type, but now with a Split PE we're never setting the selected UPE payment type.

To fix this, now that each payment method is separate, I'm wondering if we can get rid of the old `wc_stripe_selected_upe_payment_type` hidden field implementation and fetch the selected payment method directly from `$POST['payment_method']` (i.e. this would be 'stripe' or 'stripe_bancontact;).

I've been testing with this helper function below and it appears to be working but curious to get your thoughts:

```
private function get_selected_payment_method_type() {
	if ( ! isset( $_POST['payment_method'] ) && substr( $_POST['payment_method'], 0, 6 ) !== 'stripe' ) { // phpcs:ignore WordPress.Security.NonceVerification.Missing
		return '';
	}

	$payment_method_type = sanitize_text_field( wp_unslash( $_POST['payment_method'] ) );
	return substr( $payment_method_type, 0, 7 ) === 'stripe_' ? substr( $payment_method_type, 7 ) : 'card';
}
```

And then in `prepare_payment_information_from_request()` we can change the first line to be:

```
private function prepare_payment_information_from_request( WC_Order $order ) {
	$selected_payment_type = $this->get_selected_payment_method_type();
```

Since this one has been approved I'm happy to move this into a separate PR!

2024-01-19 02:20 UTC, a-danae commented
Big thanks, @james-allan for checking this out again!

And big thanks @mattallan for updating this branch, checking it with the Split PE changes, and proposing a fix! 🙌 

I've included your fix and it's testing well 🙂 There are a few tests that need adjustments, but other than that, this should be ready to review. I'll check these tomorrow.

2024-01-19 04:16 UTC, mattallan commented
No worries @a-danae! I have reviewed your latest changes and they look really good!

I also ran through the following checks:

**Checkout blocks**
  - [x] Not saving a card :+1:
  - [x] Saving a new card (4242424242424242) :+1:
  - [x] Saving a 3DS card (4000000000003220) :+1:
  - [x] Attempting to save a declining card (4000000000009995) :+1:
  - [x] Using an existing saved card :+1:
  - [x] Using an existing saved 3DS card :+1:
  - [x] Using an existing saved card that should decline after attaching (4000000000000341) :+1:
  - [x] Confirm saving a card is forced when purchasing a subscription product :+1:

**Classic checkout**
  - [x] Not saving a card :+1:
  - [x] Saving a new card :+1:
  - [x] Saving a 3DS card :+1:
  - [x] Using an existing saved card :+1:
  - [x] Using an existing saved 3DS card :+1:
  - [x] Using an existing saved card that should decline after attaching :+1:
  - [x] Confirm saving a card is forced when purchasing a subscription product :+1:

I'm happy to approve this PR. Amazing work on this one!!

2024-01-19 04:17 UTC, mattallan approved these changes

2024-01-19 09:21 UTC, merged