Add support for Oxxo & Boleto payments via the Block checkout
woocommerce/woocommerce-gateway-stripe pull request #2840
Opened 2024-01-18 07:19 UTC by james-allan

Fixes #2790

## Changes proposed in this Pull Request:

The changes in this PR are pretty small. @mattallan added most of the changes necessary to get Boleto and Oxxo to work on the block checkout page in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2823 

## Testing instructions

_These testing instructions are largely copied from Matt's PR._

**Pre-requisites**

- Separate Stripe merchant accounts located in Brazil and Mexico
- Ability to receive webhooks from Stripe (I use ngrok)

#### Testing Boleto

1. Go to **WooCommerce > Settings > General** and set your store's currency to Brazilian real (R$)
2. Go to **WooCommerce > Settings > Payments > Stripe > Settings** (panel) (/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings)
4. Click on edit keys and update the private, secret and webhook keys to your Stripe Brazil store
> [!WARNING]
> If this is not a fresh store and you are connecting a different Stripe account, you will need to go into the `usermeta` and delete the row with `meta_key` `wp__stripe_customer_id` as the existing customer ID won't exist in the Brazil store.
4. From the shop page, add a product to the cart and proceed to the block checkout
6. Enter a [valid Brazilian address](https://www.fakeaddressgenerator.com/World/Brazil_address_generator) with an email that fits the `{any_prefix}@{any_domain}` format (i.e. test@example.com)
7. Select Boleto on the checkout and enter `00.000.000/0000-00` into the text box.
8. Click on "Place Order" and you should see a pop-up window for the voucher.
9. Closing the voucher should redirect you to the order received page.
10. If you have webhooks setup properly, the order should be on-hold almost immediately.
11. Wait 3mins for the success webhook to come through and confirm the order is updated to processing

**Boleto error testing**

Stripe docs on testing Boleto: https://stripe.com/docs/payments/boleto/accept-a-payment?platform=checkout#test-integration

1. **Testing with an expired voucher**
   1. Add the product to the cart and go to the checkout
   2. While on the checkout set your email to `expire_immediately@example.com`
   3. Select Boleto and fill in the tax ID field with `00.000.000/0000-00`
   4. Placing the order should show a popup with a voucher that has expired
   5. Closing the window should send you to the order received page with a Pay link
   6. Navigate to the WooCommerce > Orders and confirm the order is set to failed status
2. **Testing invalid checkout errors**
   1. Add product to the cart and navigate to the checkout
   2. Set your country to something other than Brazil (i.e. Australia)
   3. Select Boleto and fill in the tax ID field with `00.000.000/0000-00`
   4. Placing the order should show an error on the checkout.

#### Testing Oxxo

Testing Oxxo is the same as Boleto above, except you'll need to connect a Stripe account set in Mexico and set your store's currency to **Mexican Peso**. A few things to note:

- Make sure you reset your billing email back to test@example.com or something other than `expire_immediately@example` so that the vouchers don't expire immediately.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-01-18 07:26 UTC, james-allan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> -			return [ 'result' => 'failure' ];
I changed this to be inline with my understanding of how the `process_payment()` function is intended to run. 

If you don't throw the exception here you get the following PHP error using the block checkout when an payment error occurs, and there's no detailed error message shown on the checkout. You just get a generic "something went wrong".  

```
PHP Warning:  Undefined array key "redirect" in app/public/wp-content/plugins/woocommerce/src/StoreApi/Legacy.php on line 68
```

Just noting that this change is causing the PHP tests to fail. I'll look into fixing those tomorrow.

2024-01-19 02:01 UTC, james-allan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> -			return [ 'result' => 'failure' ];
I ended up reversing this change and going with a different approach to ensuring error messages are displayed on the block checkout. see https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2840/commits/a68977db6eef7afd26a947ed804b3233a8191db6.

2024-01-19 21:48 UTC, diegocurbelo requested changes
Hey @james-allan!

I think I'm doing something wrong here, the shortcode checkout works fine, but with the blocks checkout no voucher is displayed for either Boleto or OXXO the form stays disabled, with no error in the console, and the network request succeded:

<img width="706" alt="Screenshot 2024-01-19 at 18 33 49" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/4398aa3f-bc2a-4fee-b247-acf16318b274">

<img width="829" alt="Screenshot 2024-01-19 at 18 47 28" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/be206bc1-9e67-4c2d-906e-832cf18b9032">

Also, the checkbox: `Save payment information to my account for future purchases.` should not be present for Boleto... if you check it and try to pay for the order the correct message is displayed: `This payment method cannot be saved for future use.` but I think we should hide the checkbox.

2024-01-23 01:04 UTC, james-allan commented
> I think I'm doing something wrong here, the shortcode checkout works fine, but with the blocks checkout no voucher is displayed for either Boleto or OXXO the form stays disabled

hmm ok. I'll have a look into it. Locally the modal pops up after a second. 

https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/9c56b55c-8146-4822-9f13-5dc97200152e

I'll start a JN site to rule out any local variation. FWIW, on my local site it's [this `maybeConfirmVoucherPayment()` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/block-checkout-oxxo-boleto/client/classic/upe/deferred-intent.js#L93) that shows the modal. Its in the classic checkout JS though so not sure why.

2024-01-23 05:18 UTC, james-allan commented
> I'll start a JN site to rule out any local variation. 

I set up a fresh JN site and uploaded a built version of this branch and the voucher was still displayed to me. As I mentioned above the voucher is supposed to be displayed via [this maybeConfirmVoucherPayment() function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/block-checkout-oxxo-boleto/client/classic/upe/deferred-intent.js#L93). @diegocurbelo can you confirm if that function is running for your or if that file is loaded? 
It's a classic checkout file so I don't think I should be relying on it but I've started that conversation here: p1705983085532559-slack-C055WHLA98D

2024-01-23 06:13 UTC, mattallan commented
@james-allan I've been able to replicate the issue @diegocurbelo was having by going to **WC > Settings > Advanced** and setting the checkout page to a classic/shortcode checkout page, but then when testing manually go to a checkout block page.

I wasn't getting the boleto pop-up. Then after I updated the checkout page in WC settings to a checkout block page, the voucher pop-up started working 🤔 

I need to do some digging to see what might be causing this but I wanted to share this first incase you might have a clue

2024-01-23 06:19 UTC, james-allan commented
>  by going to WC > Settings > Advanced and setting the checkout page to a classic/shortcode checkout page, but then when testing manually go to a checkout block page.

Ah nice find. I did have a similar issue back while working on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2784. IIRC I was able to fix that by updating the `has_cart_or_checkout_on_current_page()` function.

With this new information about using a separate checkout page, I've been able to replicate it too so I'll have a look into it as well.

2024-01-23 06:31 UTC, mattallan commented
@james-allan looks like the problem is just the `$stripe_params['isCheckout']` is being set to false when you're on a checkout block page that's not set as the default checkout page in WC settings.

We could change this line to:

```
$stripe_params['isCheckout'] = ( is_checkout() || has_block( 'woocommerce/checkout' ) ) && empty( $_GET['pay_for_order'] );
```

2024-01-23 08:18 UTC, james-allan commented
Thanks @mattallan. That suggestion works. I pushed that up in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2840/commits/9dbeb912cb0e29488d78802047f3a76475b7a29d.

2024-01-24 03:26 UTC, mattallan approved these changes
I've tested the latest changes and they look good to me :+1: Thanks @james-allan !

---

- [x] Checkout blocks
- [x] Classic checkout (confirm any changes didn't break existing functionality)
- [x] With both shortcode and blocks checkout pages set as default checkout.

2024-01-25 05:34 UTC, merged