Split PE - Fixes Woo Subscriptions support when using dPE
woocommerce/woocommerce-gateway-stripe pull request #2866
Opened 2024-01-29 06:32 UTC by mattallan

Fixes #2777 

## Changes proposed in this Pull Request:

This PR fixes compatibility issues with Woo Subscriptions and our new Split PE with deferred intent changes. In my testing there were two main issues I found:
1. Subscriptions purchased with an existing saved card remain on-hold after processing a renewal.
2. Attempting to purchase a subscription that had a free trial or was synced, resulted in a generic error on the checkout.
3. Error when attempting to change a subscription's payment method to an existing card.

I have addressed the above issues in the following commits:
- e2fa15d1524a36d92bae8af797a62d64c590791b - fixes the first issue by making sure we call [`maybe_update_source_on_subscription_order()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/2ff2d6815f34dac261d8ead11b11e1af8efea310/includes/compat/trait-wc-stripe-subscriptions.php#L390) whenever we're using an existing saved payment method so that the `pm_` and `cus_` tokens are saved on the subscription. This function was already being handled when a new card was being saved (see inside [`handle_saving_payment_method()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/2ff2d6815f34dac261d8ead11b11e1af8efea310/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L1848)), but not when an existing card was used.
- 9bc5fc67d5abf7e7848c06d89bc286ba4dc5567b - fixes the second issue by adding support for creating setup intents inside  `process_payment_with_deferred_intent()` for purchases that don't have an upfront payment but still require the card to be taken for future payments i.e. a subscription with a free trial. This single commit ended up being a bit larger than I typically like however, it can be broken down into the following changes:
  - Refactor the `intent_controller->create_and_confirm_setup_intent()` to handle requests from AJAX (when adding a new card) and our process_payment function. This also required slight tweaks to the JS.
  - Update the `process_payment_with_deferred_intent()` to add functionality when `$payment_needed` is false. When payment is not needed but we're inside the process_payment flow, it's expected for a setup intent to be created.
  - Make sure the stripe meta is stored on the order and saved cards handling works when both payment is needed and not needed.
  - When payment is not needed, don't process the charge and instead mark the order as complete.
- 86d3d62ead7f3a28970b7c323a786f122da318d9 - fixes the final issue by not calling `processPayment` when a customer is changing payment method to an existing saved card.

## Testing instructions

Before testing, make sure you have:
- the latest Woo Subscriptions installed and activated,
- a simple subscription product and another with a free trial period

There are a lot of subscription flows to cover and rather than go through them all here, I'll link to our testing instructions for the critical subscription flows:
- [Shopper subscription flows](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#shopper-subscriptions-1)
- [Merchant subscription flows](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#merchant-subscriptions-1)

#### Purchasing and renewing subscriptions

1. Add the simple subscription product to your cart
2. Navigate to the checkout page and confirm only reusable payment methods are visible
3. Complete the checkout using a new card
4. Visit WP Admin > WooCommerce > Subscriptions and view the newly purchased subscription
5. On the Edit Subscription admin page, click on the pencil icon in the Billing Details section and confirm the Stripe customer ID and source ID (`pm_1234`) are correctly saved on the subscription ![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/d2eadda1-6c9b-44de-afcf-e9043b20297a)
6. Use the Order Actions to process an automatic renewal for the subscription: ![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/083b342f-998a-408a-ac77-82d11166cedf)
7. Confirm the renewal order is created and is processing, and confirm the subscription is active.
8. Confirm the payment in Stripe

#### Purchasing and renewing subscriptions with setup intents

1. Follow the above steps except this time add a subscription product with a trial period
2. Confirm the new card you added above, is now in your list of saved cards (to confirm new cards used to purchase subscriptions are always saved)
3. Use a saved card this time instead of adding a new one
4. Confirm there's no payment for the initial purchase.
5. After processing a renewal order, confirm the charge in Stripe.

#### Changing subscriptions payment method

> [!NOTE]
> Before running this test, make sure you have at least 2 active subscriptions to test updating all payment methods.

1. From the frontend of your store, go to My Account > Subscriptions and click to view one of your active subscriptions
2. Click on the Change payment button![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/e128e594-f5ca-4ee7-a846-9a02448f3b96)
3. Choose a new card number that differs from your existing card i.e. if your subscription has the visa `4242424242424242`, change the payment to mastercard `5555555555554444` so it's easier to notice the difference
6. Check the "Update the payment method used for all of my current subscriptions (optional)" box and submit the form
7. Go back to My Account > Subscriptions to confirm all of your active subscriptions now have the updated payment method ![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/84f9db84-9328-4d1b-9ca5-8cdaa29724a9)
8. Process a subscription renewal using the Edit Subscription actions shown in the previous tests and confirm the new/changed card is used to process the subscription.

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-01-29 06:36 UTC, mattallan commented
I've performed the following tests on this PR:

### Classic checkout/shortcode

- [x] Purchase a simple subscription :+1:
    - [x] Using an existing saved card
    - [x] Using a new card (confirmed card is saved)
- [x] Purchase trial/synced subscription :+1:
    - [x] Using an existing saved card
    - [x] Using a new card (confirmed card is saved)
    - [x] Confirm setup intent is created
- [x] Purchase multiple subscriptions :+1:
    - [x] Confirm pm_ and cus_ ids are present on all active subscriptions
- [x] Confirm payment methods displayed on checkout when a subscription is in the cart :+1:
- [x] Manually pay for renewal order :+1:
- [x] Renew early via shortcode checkout from My Account > Subscriptions > View Subscription > Renew now :+1:
- [x] Automatic subscription renewal for subscriptions purchased on classic checkout (both simple & trial products) :+1:

### Checkout Blocks

- [x] Purchase a simple subscription
    - [x] Using an existing saved card
    - [x] Using a new card (confirmed card is saved)
- [x] Purchase trial/synced subscription 
    - [x] Using an existing saved card
    - [x] Using a new card (confirmed card is saved)
- [x] Purchase multiple subscriptions
    - [x] Confirm pm_ and cus_ ids are present on all active subscriptions
- [x] Confirm payment methods displayed on checkout when a subscription is in the cart
- [x] Manually pay for renewal order
- [x] Renew early via checkout block from My Account > Subscriptions > View Subscription > Renew now
- [x] Renew subscriptions automatically for subscriptions that were purchased on checkout block

### Other subscription-related tests

- [x] Change payment method
    - [x] New card
    - [x] Existing card
    - [x] Update all existing subscriptions with new card
    - [x] Update all existing subscriptions with existing card
- [x] Renew early via modal

2024-01-31 02:02 UTC, mattallan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +				$payment_intent = $this->process_setup_intent_for_order( $order, $payment_information );
In the existing `process_payment()` method, we have the following code which handles the 'change_payment_method' flow separately:

```
if ( $this->maybe_change_subscription_payment_method( $order_id ) ) {
	return $this->process_change_subscription_payment_method( $order_id );
}
```

While working on this PR, I couldn't find a need to handle these requests separately. Am I missing something here?

2024-01-31 02:09 UTC, mattallan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +				$payment_intent = $this->process_setup_intent_for_order( $order, $payment_information );
Hmm actually, looking at the `process_change_subscription_payment_method()` there are some differences:

- It throws a `do_action( 'wc_stripe_change_subs_payment_method_success' );` before returning
  - I can't see this hook being used by anything, but it's technically a breaking change so we can add it back.
- It doesn't call `$order->payment_complete()`
  - Calling `WC_Subscription::payment_complete()` exits on the first line if the request is to change a payment method so this is already being handled by Woo Subscriptions. I think it's better to still not even call payment complete while we're handling a change payment method request, so I'll update this PR.

I can't see the hook being used anyway

2024-01-31 03:33 UTC, mattallan commented on includes/class-wc-stripe-intent-controller.php
> +		if ( isset( $payment_information['level3'], $payment_information['order'] ) ) {
According to [Stripe's setup_intent documentation](https://stripe.com/docs/api/setup_intents/create), level3 data isn't a parameter of the create requrest, so I'll have to remove this.

2024-01-31 06:24 UTC, mattallan commented on includes/class-wc-stripe-intent-controller.php
> +		if ( isset( $payment_information['level3'], $payment_information['order'] ) ) {
Removed in 6a589487da392b3c902cc60a0e9975fc23389809

2024-01-31 06:25 UTC, mattallan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +				$payment_intent = $this->process_setup_intent_for_order( $order, $payment_information );
I've just pushed up 10591299491085df343f37f2211d00c24d7c1490 which fixes the two issues above by:

- making sure `do_action( 'wc_stripe_change_subs_payment_method_success' )` is triggered inside process_payment_with_deferred_intent()
- don't call `$order->payment_complete()` when changing a subscriptions payment method.

2024-02-01 06:23 UTC, james-allan commented
Hey @mattallan I've been trying to make some subscription purchases using other payment methods like Bancontact. [Stripe's doc](https://stripe.com/docs/payments/bancontact) suggest that Bancontact can be used for recurring revenue via SEPA Debit. Stipe will do the Bancontact -> SEPA stuff under the hood as long you send the required setup intent, off session args etc. 

However when I attempted to purchase a subscription using Bancontact I got a number of rolling issues: 

1. We need to send mandate data when using Bancontact with setup intents for off session payments. See stripe error below.
2. When I resolved that issue, I then had a different issue when `create_payment_token_for_user()` is called. The `$payment_method` doesn't have any last and so the creating of a `WC_Payment_Token_SEPA` fails.

<img width="523" alt="Screenshot 2024-02-01 at 3 53 30 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/334161ac-3869-48f7-90f2-33a02b0411df">

I'm not sure how you think we should proceed here. If theres a lot of unknowns here perhaps we limit the scope of this PR to card payments and work on other APMs in a separate PR. Thoughts?

2024-02-01 06:26 UTC, james-allan commented
> [Stripe's doc](https://stripe.com/docs/payments/bancontact) suggest that Bancontact can be used for recurring revenue via SEPA Debit.

WooPayments have Bancontact as not a reusable payment method so perhaps there's more to this that make it now possible. 🤔

2024-02-01 07:03 UTC, james-allan commented
> I've been trying to make some subscription purchases using other payment methods like Bancontact.

So it turns out I had manual payments enabled with Subscriptions which is why Bancontact was showing up originally. If I disable manual payments, it is now longer shown. 

That changes the question slightly because we do still need to resolve those errors but I wonder if we need to change it so we only create set up intents for off session payments if we're creating an automatic subscription. 🤔

2024-02-01 10:09 UTC, mattallan commented
@james-allan Thanks for taking a look at this one.

Since some of our APMs are listed as reusable, they should still technically work for subscription purchases and so I had a look at what is stopping us from accepting an APM like Bancontact to purchase a subscription product.

Here's what I found needs to change:
- add `'subscriptions'` to list of $supports flags on each UPE payment method that is reusable.
- update our `is_mandate_data_required()` function so that it also includes bancontact (which uses SEPA for tokenization)
- Need to update our `process_payment_with_deferred_intent()` function so that it doesn't try to save a payment token until after the customer has gone through the confirmation/authorization pop-up. This is just a theory but, to add a WC token we need the last4 value and we don't have the last4 value for our redirecting payment methods until the customer has been redirected. I think we have to add/save the payment token on redirect for these.

There's a fair bit to change here but I'm happy to continue adding those changes to this PR unless you think it's best to separate them?
Smaller PRs might be better but I don't mind either way! Do you have a preference?

2024-02-02 01:13 UTC, james-allan commented
> Need to update our process_payment_with_deferred_intent() function so that it doesn't try to save a payment token until after the customer has gone through the confirmation/authorization pop-up. This is just a theory but, to add a WC token we need the last4 value and we don't have the last4 value for our redirecting payment methods until the customer has been redirected. I think we have to add/save the payment token on redirect for these.

I'm not sure how far down this rabbit hole you went but from my testing payment methods like Bancontact don't return the last 4 even once you've approved the payment and returned to the store. 

| Bancontact | SEPA |
|--------|--------|
| <img width="426" alt="Screenshot 2024-02-02 at 11 00 53 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/aa60a7c7-d75d-42e0-a02c-c01cbed71419"> | <img width="426" alt="Screenshot 2024-02-02 at 11 00 26 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/6ecd1745-e5a4-49c2-b410-12933d058a22"> | 

Above is the response from the `/payment_methods` endpoint via the `WC_Stripe_API::get_payment_method()` function. 

You'll notice that the SEPA PM response includes additional details like last4 whereas the Bancontact has essentially no information. Looking at Stripe docs, this appears to be the correct response. The [Bancontact arg](https://stripe.com/docs/api/payment_methods/object#payment_method_object-bancontact) has no child args, but [SEPA](https://stripe.com/docs/api/payment_methods/object#payment_method_object-sepa_debit) does. I _think_ (I could be wrong) but this could mean Bancontact PMs cannot ever return a last4.  

> Smaller PRs might be better but I don't mind either way! Do you have a preference?

I think its fair to move this to a separate issue given there's additional research we'll need to do to investigate if Bancontact can be used as a saved token. As I mentioned, WooPayments have it as a non-resuable method, our Stripe plugin is torn on the topic because the `WC_Gateway_Stripe_Bancontact` class [doesn't list `tokenization` or `subscriptions` as a feature](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7.9.1/includes/payment-methods/class-wc-gateway-stripe-bancontact.php#L71-L74) of that gateway, but the `WC_Stripe_UPE_Payment_Method_Bancontact` class says it is reusable. 🤷

2024-02-02 01:35 UTC, mattallan commented
Thanks @james-allan for going further than I did! I didn't get that far to confirm whether the last4 would be on the payment method object after finishing/confirming the Bancontact payment. 

> I think its fair to move this to a separate issue given there's additional research we'll need to do to investigate if Bancontact can be used as a saved token. As I mentioned, WooPayments have it as a non-resuable method, our Stripe plugin is torn on the topic because the WC_Gateway_Stripe_Bancontact class [doesn't list tokenization or subscriptions as a feature](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7.9.1/includes/payment-methods/class-wc-gateway-stripe-bancontact.php#L71-L74) of that gateway, but the WC_Stripe_UPE_Payment_Method_Bancontact class says it is reusable.

I agree with this comment and happy to handle this in a separate PR as it sounds like we'll need to do a bit more investigation into supporting automatic subscription renewals using our APMs.

2024-02-02 05:51 UTC, james-allan commented
> I agree with this comment and happy to handle this in a separate PR as it sounds like we'll need to do a bit more investigation into supporting automatic subscription renewals using our APMs.

Ok, I've created the issue to add the other APMs here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2872

2024-02-02 08:07 UTC, james-allan requested changes
Changes look good @mattallan. 

I've tested the following scenarios: 

1. Standard subscription purchase. 👍 
2. Free trial subscription. 👍 
3. Signing up using a saved card. 👍 
4. Early renewal order processed 👍 
5. Sign up to free trial using 3DS card ❌ I got an `invalid_intent_id` error message on checkout and the following error in my logs: 

```
PHP Warning:  Undefined property: stdClass::$latest_charge in /wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 717
```

<img width="584" alt="Screenshot 2024-02-02 at 5 32 43 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/de73087d-2751-4876-bada-afeab11d05d5">

FWIW the invalid intent error appears to be caused because the order doesn't have an intent stored on it but the `update_order_status_ajax()` request receives a setup intent id. ie `seti_1OfHMMCM0qfKgPGttSXXo0ZI !== ''`. 

I think this means `update_order_status_ajax()` needs to be changed to handle receiving setup intents and intents. eg if it recevies a set up intent, see if the order has a corresponding set up intent. At the moment it just pulls the payment intent order meta which is empty in this case. 

6. Standard sign up using 3DS card 👍 
7. Renewal run via Action scheduler. 👍
8. Multiple subscriptions (weekly and monthly) 👍

2024-02-02 08:07 UTC, james-allan commented on includes/class-wc-stripe-intent-controller.php
> +	public function create_and_confirm_setup_intent( $payment_information ) {
Just noting that this isn't breaking any backwards compatibility as this function is unreleased as it was introduced in the `add/deferred-intent` branch.

2024-02-02 08:07 UTC, james-allan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +			} else if ( $payment_information['is_using_saved_payment_method'] ) {
```suggestion
			} elseif ( $payment_information['is_using_saved_payment_method'] ) {
```
Nit: [Use elseif, not else if](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#use-elseif-not-else-if)

2024-02-02 08:07 UTC, james-allan commented on client/api/index.js
> +	 * @param {Object} paymentMethod The id of the payment method.
```suggestion
	 * @param {Object} paymentMethod      Payment method data.
	 * @param {string} paymentMethod.id   The ID of the payment method.
	 * @param {string} paymentMethod.type The type of the payment method.
```

Minor: I just noticed this param changed but the description wasn't updated. This suggested change matches with [WP JS documentation standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/#functions).

2024-02-02 08:07 UTC, james-allan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> -				if ( $payment_information['save_payment_method_to_store'] ) {
Just so I've got this right in my head, this section of changes essentially move the handling of saving the payment method out of the `payment_needed` logic because in some subscription cases (free trials) we need to save the payment method even if payment isn't needed. 

ie saving a payment method is now allowed irrespective of payment being needed or not. Is that right?

2024-02-05 00:48 UTC, mattallan commented on includes/class-wc-stripe-intent-controller.php
> +	public function create_and_confirm_setup_intent( $payment_information ) {
Correct :) Thanks for checking!

2024-02-05 00:51 UTC, mattallan commented on client/api/index.js
> +	 * @param {Object} paymentMethod The id of the payment method.
Thanks James!

2024-02-05 01:47 UTC, mattallan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> -				if ( $payment_information['save_payment_method_to_store'] ) {
Yeah exactly. Do you have any concerns with this?

> ie saving a payment method is now allowed irrespective of payment being needed or not. Is that right?

Yeah, but to clarify this a bit further. WooCommerce doesn't trigger the gateway->process_payment function for $0 orders by default. Other plugins like Woo Subscriptions hooks onto the `woocommerce_order_needs_payment` filter to make sure that the payment is processed for any subscription that has a future payment, so for these cases in Stripe we still want to save the payment method.e

2024-02-05 01:48 UTC, mattallan commented
Thanks for taking a look and testing this @james-allan 

> Sign up to free trial using 3DS card :x:

Good catch! I'll look into this one!

2024-02-05 06:35 UTC, mattallan commented
@james-allan I've just pushed up [1668359](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2866/commits/1668359db3299b988a30efc2935a935841dc9bbc) to fix the issue with using a 3DS card to purchase subscription product with no upfront cost (i.e. trial/synced).

Something I also noticed while reviewing the code is that I was completing orders (and activating subscriptions) before the customer is redirected to an authentication modal. I pushed up [3eecfc4](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2866/commits/3eecfc42f12d865c33b0950e1ca1853436ca9536) to fix this.

2024-02-06 05:12 UTC, james-allan approved these changes
Changes look good and work well. I just noticed a slightly confusing sentence in the new function comment you introduced. Otherwise this looks good to go.

2024-02-06 05:12 UTC, james-allan commented on includes/class-wc-stripe-helper.php
> +	 * Returns the payment intent or setup intent id method ID from a given intent object.
```suggestion
	 * Returns the payment intent or setup intent ID from a given order object.
```

2024-02-06 05:14 UTC, mattallan commented on includes/class-wc-stripe-helper.php
> +	 * Returns the payment intent or setup intent id method ID from a given intent object.
Reads well to me 😂🙈

2024-02-06 05:14 UTC, merged