Using the preferred brand when paying with co-branded CC
woocommerce/woocommerce-gateway-stripe pull request #3030
Opened 2024-03-28 22:53 UTC by wjrosa

Fixes #

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-04-22 06:22 UTC, james-allan requested changes
@wjrosa I've left an initial review, however I'm not sure what this PR is actually doing yet. It requires WooCommerce 8.9 which hasn't released yet but if that requirement is met and the payment method has a preferred brand, it will record that in order meta.

Are there further changes coming that makes use of the value stored in `_stripe_card_brand`?

2024-04-22 06:22 UTC, james-allan commented on includes/class-wc-stripe-co-branded-cc-compatibility.php
> +if ( ! defined( 'ABSPATH' ) ) {
The Stripe plugin appears to lack a lot of file header comments, however it is a recommendation in the official php documentation standards (https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#6-file-headers). 

```suggestion
/**
 * Stripe Co-branded cards compatibility class.
 *
 * @package WooCommerce Stripe
 * @since 8.3.0
 */
 
if ( ! defined( 'ABSPATH' ) ) {
```

2024-04-22 06:22 UTC, james-allan commented on includes/class-wc-stripe-co-branded-cc-compatibility.php
> +
```suggestion
	/**
	 * Determines whether the current version of WooCommerce is supported.
	 *
	 * @return bool
	 */
```

2024-04-22 06:22 UTC, james-allan commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +				wc_admin_record_tracks_event( 'wcstripe_co_branded_cc_preferred_brand_selected', [ 'brand' => $preferred_brand ] );
Does this `wc_admin_record_tracks_event()` need to be wrapped in a `function_exists()` check? 

I noticed basically everywhere else it is used in Stripe and WooPayments, they first check if it exists. 

My concern is that the `wc_admin_record_tracks_event()` has admin in the function name and it's buried in a react-admin folder I haven't had this lead to an error but I'm not sure if we want to rely on an admin function in front end code.

2024-04-22 16:42 UTC, wjrosa commented on includes/payment-methods/class-wc-stripe-upe-payment-gateway.php
> +				wc_admin_record_tracks_event( 'wcstripe_co_branded_cc_preferred_brand_selected', [ 'brand' => $preferred_brand ] );
Makes sense! Added a check for it

2024-04-22 16:52 UTC, wjrosa commented
> @wjrosa I've left an initial review, however I'm not sure what this PR is actually doing yet. It requires WooCommerce 8.9 which hasn't released yet but if that requirement is met and the payment method has a preferred brand, it will record that in order meta.
> 
> Are there further changes coming that makes use of the value stored in `_stripe_card_brand`?

Thanks for your review!

> however I'm not sure what this PR is actually doing yet
It sends the selected card brand to Stripe instead of the default one when paying for an order.

> It requires WooCommerce 8.9 which hasn't released yet but if that requirement is met and the payment method has a preferred brand, it will record that in order meta.
The supported version is actually a dummy value since I am not sure when the next release will be (I will update it once it is released). The best way to test it is by hardcoding `true` to the compatibility class and using the latest version available in `[trunk](https://github.com/woocommerce/woocommerce)`.

 > Are there further changes coming that makes use of the value stored in _stripe_card_brand?
Not really, that was just to make unit testing easier honestly. I could not find a good way to test the new param being sent to Stripe.

2024-04-23 00:13 UTC, james-allan commented
> It sends the selected card brand to Stripe instead of the default one when paying for an order.

Oh. I was trying to test that but even on `develop` the transactions in Stripe were correctly recording the card brand and when I looked at the changes on this PR it just looks like it calls `set_preferred_card_brand_for_order()` which just sets the `_stripe_card_brand` order meta data. 

For example on `develop` 


| Visa | Cartes Bancaires |
|--------|--------|
| <img width="1132" alt="Screenshot 2024-04-23 at 10 06 55 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/14d9967c-3969-4522-aaa7-4f1c80b34e00"> | <img width="1100" alt="Screenshot 2024-04-23 at 10 05 37 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/e766d157-fce6-4de2-9b53-265185733f97"> |
| <img width="545" alt="Screenshot 2024-04-23 at 10 07 14 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/cb3453b6-eef2-4f2e-b74a-9796a8105e4a"> | <img width="493" alt="Screenshot 2024-04-23 at 10 05 58 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/719be69e-4ec2-4810-bd40-9ad55686a470"> |

I'm new to testing this card brand stuff so let me know if I'm missing anything.

2024-04-23 15:27 UTC, wjrosa commented
> > It sends the selected card brand to Stripe instead of the default one when paying for an order.
> 
> Oh. I was trying to test that but even on `develop` the transactions in Stripe were correctly recording the card brand and when I looked at the changes on this PR it just looks like it calls `set_preferred_card_brand_for_order()` which just sets the `_stripe_card_brand` order meta data.
> 
> For example on `develop`
> 
> Visa	Cartes Bancaires
> <img alt="Screenshot 2024-04-23 at 10 06 55 am" width="1132" src="https://private-user-images.githubusercontent.com/8490476/324643706-14d9967c-3969-4522-aaa7-4f1c80b34e00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODUyMTIsIm5iZiI6MTcxMzg4NDkxMiwicGF0aCI6Ii84NDkwNDc2LzMyNDY0MzcwNi0xNGQ5OTY3Yy0zOTY5LTQ1MjItYWFhNy00ZjFjODBiMzRlMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTUwODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI3MzEwYWZlNTE0ZDBlNWJjZmU2MTIwMmU0OGE0NTgwOTdjODFiNzE1NzlmMTIzMGJjYTZhNTBiMjNhMzAxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jX4ZFaf3v_mswnwSCLbw6QsWb7DK71KgSaFcLjxmGL4">	<img alt="Screenshot 2024-04-23 at 10 05 37 am" width="1100" src="https://private-user-images.githubusercontent.com/8490476/324643859-e766d157-fce6-4de2-9b53-265185733f97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODUyMTIsIm5iZiI6MTcxMzg4NDkxMiwicGF0aCI6Ii84NDkwNDc2LzMyNDY0Mzg1OS1lNzY2ZDE1Ny1mY2U2LTRkZTItOWI1My0yNjUxODU3MzNmOTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTUwODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDY0YzRjMDQ3ZTdmMDhjNTVkZTkwNWQwOTg0ZTA1YzRjNTgzODZhYWMyODk2M2RiMjA0NTJkOTJkYzhiMjVlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kGy8_qbpZAZjz3lKI9qFLbKf2n0pggqbqN8NpvJSjsA">
> <img alt="Screenshot 2024-04-23 at 10 07 14 am" width="545" src="https://private-user-images.githubusercontent.com/8490476/324643698-cb3453b6-eef2-4f2e-b74a-9796a8105e4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODUyMTIsIm5iZiI6MTcxMzg4NDkxMiwicGF0aCI6Ii84NDkwNDc2LzMyNDY0MzY5OC1jYjM0NTNiNi1lZWYyLTRmMmUtYjc0YS05Nzk2YTgxMDVlNGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTUwODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFiYmEwNTc1MWQ2ZTc5ZTNlMDg5YjZkY2EyMzAzODIyZTgyNDQyOWM0OGZhZWVjMWQ5M2FkODMwMjE5MDhjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9v5wq5nFeVNlbs8boK6K6_3oKWR0mzNz5ISIAG-9a0Q">	<img alt="Screenshot 2024-04-23 at 10 05 58 am" width="493" src="https://private-user-images.githubusercontent.com/8490476/324643725-719be69e-4ec2-4810-bd40-9ad55686a470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODUyMTIsIm5iZiI6MTcxMzg4NDkxMiwicGF0aCI6Ii84NDkwNDc2LzMyNDY0MzcyNS03MTliZTY5ZS00ZWMyLTQ4MTAtYmQ0MC05YWQ1NTY4NmE0NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTUwODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWI0OWEzNGI5N2MyMDQwMWI1OTIyMzQxNmU4ZDVjNDE4NmM5Y2M3OGZhN2NmNTRmOTNiNzYyMGIwYjRiOTA3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a39IZkj03oX8tYVQ_x70n94gVEYMbgF5OQPM89PUJfM">
> I'm new to testing this card brand stuff so let me know if I'm missing anything.

Oh, sorry, there were two issues with this PR:
1 - The original implementation for the use of the preferred card brand was removed incorrectly on my PR that added tracking for the brand when I merged it to this branch
2 - That implementation was done in both the payment intent creation and update. [While the documentation says it is supported only at payment intent update (confirm)](https://docs.stripe.com/api/payment_intents/object#payment_intent_object-payment_method_options-card-network). 

This PR now updates the preferred brand when reusing a payment intent. Example:
- You started to pay for an order using a co-branded credit card, but it failed
- You just tried again afterward using another (working) co-branded credit card or another working brand for the same card
In this case, we will reuse the payment intent associated with the order and update the selected brand

Unfortunately, Stripe does not have a co-branded test card for failures, so we cannot test this case. I guess the only testable thing would be the meta.

Thanks for confirming it; otherwise, I wouldn't have noticed it 🤦 .

2024-04-26 05:22 UTC, james-allan approved these changes
> - You started to pay for an order using a co-branded credit card, but it failed
> - You just tried again afterward using another (working) co-branded credit card or another working brand for the same card
>
> Unfortunately, Stripe does not have a co-branded test card for failures, so we cannot test this case. I guess the only testable thing would be the meta.

I tried to test it by making the payment fail due to an invalid request (ie dummy `capture_method`). What I did was have it fail when I used Visa or MasterCard, then make it succeed when using Cartes Bancaires and vice versa even then on `develop` it worked fine and recorded the correct brand in Stripe so IDK. 🤷

I'm happy to approve this if you think its necessary though.

2024-04-26 13:48 UTC, wjrosa commented
> > * You started to pay for an order using a co-branded credit card, but it failed
> > * You just tried again afterward using another (working) co-branded credit card or another working brand for the same card
> > 
> > Unfortunately, Stripe does not have a co-branded test card for failures, so we cannot test this case. I guess the only testable thing would be the meta.
> 
> I tried to test it by making the payment fail due to an invalid request (ie dummy `capture_method`). What I did was have it fail when I used Visa or MasterCard, then make it succeed when using Cartes Bancaires and vice versa even then on `develop` it worked fine and recorded the correct brand in Stripe so IDK. 🤷
> 
> I'm happy to approve this if you think its necessary though.

That's weird. But anyway, that's how Stripe advises to do the integration ([see this](https://docs.stripe.com/api/payment_intents/confirm#confirm_payment_intent-payment_method_options-card-network)). And at least, this PR has some code improvements anyway. Thanks for the review!

2024-04-26 13:55 UTC, merged