Add Klarna to the available payment methods
woocommerce/woocommerce-gateway-stripe pull request #3040
Opened 2024-04-04 05:28 UTC by a-danae

Fixes #3043 

## Changes proposed in this Pull Request:

- Accept payments with Klarna using the Updated checkout experience. 

## Testing instructions

Find the testing instructions in [v8.3.0 ‐ Release testing instructions](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/v8.3.0-%E2%80%90-Release-testing-instructions#klarna)

---

-   [x] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [x] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-04-24 06:54 UTC, james-allan requested changes
Hey @a-danae. This PR is looking pretty good. I left 2 initial review comments which are a minor comment and fixing an error.

I ran through the following tests. Noting that I tested with an account based in the US. I also ran some basic tests on a AU account just to make sure things work there too. 

**Checkout**
- [x] Not shown for subscription purchases. 
- [x] Not shown for purchases not in invalid currency.
- [x] Not shown when billing address is in invalid country.
- [x] ⚠️ Purchase outside the merchants base location (ie based in the US, customer in AU). 
     -  There's an error that occurs on the checkout but it seems irrelevant to the actual underlying issue. See errors below.

| Checkout Error    | Stripe Error |
| -------- | ------- |
| <img width="1161" alt="Screenshot 2024-04-24 at 3 10 05 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/8cbde4ba-368f-4ab6-97a8-1cfbfba38e65"> | <img width="600" alt="Screenshot 2024-04-24 at 3 11 45 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/224dc85b-2697-46e2-97d7-70a38456325f">  |

- [x] Completed purchase using 4 installments. 
- [x] Abandon payment (don't confirm after checkout submit).
    - There's an error notice shown on the shortcode checkout indicating payment couldn't be completed. There's no notice on the block checkout though I think it's primed and refreshing the page will make it show. (see below). 
 
<img width="600" alt="Screenshot 2024-04-24 at 3 19 58 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/634557e2-1859-4c97-9e37-d302d9f1733d">

**Pay for Order**
- [ ] Not shown for purchases not in invalid currency.
- [x] Completed purchase. 

**My Account**
- [x] Not shown on payment methods page. 
- [ ] Cannot add saved token. 

**Admin**
- [x] Order correctly records Klarna as the Payment method.
- [ ] Full Refunds
- [ ] Partial Refunds

**Stripe Dashboard**
- [ ] Payments correctly reflect Klarna as the Payment method.
- [ ] Refunds

**Testing instructions**

- [ ] Double check the tests I've ran cover the official testing instructions in [v8.3.0 ‐ Release testing instructions](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/v8.3.0-%E2%80%90-Release-testing-instructions#klarna)

#### A comment on designs

This is a minor thing and I'd suggest we handle them separately as to not unnecessarily hold up this PR, but in the designs for WooPayments that we're basing our on, I noticed their Klarna icon in the admin section and on the block checkout is filled, whereas ours has a white section

| Designs    | Current |
| -------- | ------- |
| <img width="300" alt="Screenshot 2024-04-24 at 2 47 39 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/bb5e1b05-8bbe-478d-bb41-1dadc7b6a917"><img width="150" alt="Screenshot 2024-04-24 at 2 48 17 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/ada07edf-dba3-419e-a58f-fca6535f6f9c"> | <img width="300" alt="Screenshot 2024-04-24 at 4 53 26 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/54eeb990-35a6-402e-bb61-bd3701e88b3c"><img width="150" alt="Screenshot 2024-04-24 at 4 52 51 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/424a9270-e661-4e16-a927-89f6bc99af02"> |

I'll continue testing on Friday as I'll be afk tomorrow. :)

2024-04-24 06:54 UTC, james-allan commented on client/stripe-utils/utils.js
> + * Hides payment method if it has set specific countries in the PHP class.
```suggestion
 * Determines if the payment method is restricted to specific countries. 
```

I note that this is a copy of WooPayments function but just a minor suggestion. This function description suggests that it will hide the payment element when in fact it just returns a bool that can be used for that purpose.

2024-04-24 06:54 UTC, james-allan commented on client/stripe-utils/utils.js
> +		wcpayCustomerData?.billing_country ||
This `wcpayCustomerData` won't exist in the Stripe context. I think it needs to be `getStripeServerData()`

<img width="652" alt="Screenshot 2024-04-24 at 2 15 09 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/e1b2fb61-371a-4061-99a7-aaca25323ff1">

2024-04-24 06:54 UTC, james-allan commented on client/stripe-utils/utils.js
> +		wcpayCustomerData?.billing_country ||
Looking into this a little more, the `getStripeServerData()` which comes from the `wc_stripe_upe_params` localized params which are generated in [this  `javascript_params()` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/klarna-payment-method/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L355) doesn't include the billing country.

We might need to do something similar to this: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/klarna-payment-method/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L2002-L2016

2024-04-24 18:16 UTC, a-danae commented on client/stripe-utils/utils.js
> + * Hides payment method if it has set specific countries in the PHP class.
True, thanks! 🙂 Suggestion committed.

2024-04-24 20:02 UTC, a-danae commented on client/stripe-utils/utils.js
> +		wcpayCustomerData?.billing_country ||
Whoops. Great catch! Updated in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3040/commits/09dd5b8b78c3103e92308369e005d0a95858966a

2024-04-25 17:56 UTC, a-danae commented
Thanks for the review so far, @james-allan ! 🙂 

I've created a couple of issues for these behaviors:

> ⚠️ Purchase outside the merchants base location (ie based in the US, customer in AU).
There's an error that occurs on the checkout but it seems irrelevant to the actual underlying issue. See errors below.

This is also happening in WooPayments btw. I opened an issue over there too.
- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3096

> in the designs for WooPayments that we're basing our on, I noticed their Klarna icon in the admin section and on the block checkout is filled, whereas ours has a white section

Not blocking this PR makes sense to me! Here's the related issue
- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3097

2024-04-25 22:47 UTC, james-allan commented on client/stripe-utils/utils.js
> +		wcpayCustomerData?.billing_country ||
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3040/commits/09dd5b8b78c3103e92308369e005d0a95858966a

2024-04-26 03:28 UTC, james-allan approved these changes

2024-04-26 03:29 UTC, james-allan commented
Changes look good. I've finished all my testing instructions and reviewed the list you mentioned in the 8.3 list. :)

2024-04-26 17:32 UTC, merged