Allow customizing the label and description of the UPE payment methods
woocommerce/woocommerce-gateway-stripe pull request #3176
Opened 2024-06-04 17:32 UTC by Mayisha

Fixes #2993 

## Changes proposed in this Pull Request:

## Testing instructions

2024-06-06 20:03 UTC, diegocurbelo requested changes
Thanks for working on this @Mayisha.

The code looks good, I think we should check if UPE is enabled server-side it would make the code cleaner.

It works great in the new checkout experience:
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/137895c6-6216-406a-8a95-4a967891a406)

It also works with empty titles/description:
![image copy](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/8ec72b2b-dea1-4a0d-bb8b-b4448ebd9cde)


The only detail is the position of the customize button with payment methods with short descriptions like Klarna... we need to align the button to the right.

![Screenshot 2024-06-06 at 4 23 35 PM](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/332e9fc4-fc38-4dea-9071-5a1fb9000e64)

2024-06-06 20:03 UTC, diegocurbelo commented on includes/admin/class-wc-rest-stripe-settings-controller.php
> +		$is_upe_enabled    = $request->get_param( 'is_upe_enabled' );
Instead of getting the `$is_upe_enabled ` from the front-end, we can get it directly server side.

2024-06-07 15:29 UTC, Mayisha commented
Thanks @diegocurbelo :rocket: 

I have fixed the button in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3176/commits/0efdc2db3c8a8a8ef72ed3bbd53e3f04f5280d98 and now I am checking the UPE status on the server side which is fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3176/commits/048c2f4312ff5ff1adfe4b86db83f623cefd4803.

2024-06-09 17:44 UTC, diegocurbelo approved these changes
Thanks for making the changes @Mayisha!

Looks great now! 🚢

2024-06-14 04:49 UTC, merged