Reword statement descriptor preview title
woocommerce/woocommerce-gateway-stripe pull request #3201
Opened 2024-06-11 19:10 UTC by wjrosa

Fixes #3199

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-06-12 02:01 UTC, james-allan reviewed
The changes look good to me. 

As a general comment, these bank statement previews are getting more complicated or even irrelevant depending on which payment methods you have enabled. 

Saying "most" is hard for a merchant to understand.

One way to resolve this would be to include a Cash App example (see mockup below). 

<img width="770" alt="Screenshot 2024-06-12 at 11 57 28 AM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/d97ea623-80e5-4f37-8df8-021c73d41541">

Or add a tip that helps explain what "most" means. 

What are your thoughts @wjrosa?

2024-06-12 04:20 UTC, james-allan commented
> The unbalanced nature of having 3 previews is not great. :/

Fitting them 3 across might as an option work too. 

<img width="782" alt="Screenshot 2024-06-12 at 2 19 54 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/0241c811-6ed1-45e3-acd8-eba45fab4418">

2024-06-12 18:02 UTC, wjrosa commented
> > The unbalanced nature of having 3 previews is not great. :/
> 
> Fitting them 3 across might as an option work too.
> 
> <img alt="Screenshot 2024-06-12 at 2 19 54 PM" width="782" src="https://private-user-images.githubusercontent.com/8490476/338821605-0241c811-6ed1-45e3-acd8-eba45fab4418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDYyMjcsIm5iZiI6MTcxODIwNTkyNywicGF0aCI6Ii84NDkwNDc2LzMzODgyMTYwNS0wMjQxYzgxMS02ZWQxLTQ1ZTMtYWNkOC1lYmE0NWZhYjQ0MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMTUyNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk3MjYzYTgxMTg3Njc2ZTEwNDU0N2M5MjY2YTYwZDlkZWJiZWY2OTA4NzgxY2U5ZmQ0YTQwYzA0MmExNGFmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dQz9boIskM-EAHybLItUuv8x6YV6swucnQ8rzQhYVbE">

Thank you, @james-allan ! Your last suggestion makes much more sense. I have adopted it (PR updated with it):
![Screenshot 2024-06-12 at 15 01 46](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/b50f7262-784b-4d2c-a28d-806d763524b3)

2024-06-13 03:02 UTC, james-allan commented
There seems to be an issue with the alignment of the icons:

<img width="1470" alt="Screenshot 2024-06-13 at 10 19 35 AM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/7c8d1070-501d-45a7-afa1-c479ad344c5d">

On the right is when there are only 2 previews and things look fine. However on the left when there are 3 previews, the icons are unaligned. I spent a bit of time looking into what's causing that, however I wasn't able to find a solution. 

I think it's caused by the previews that overflow to 2 lines in the title. 

<img width="682" alt="Screenshot 2024-06-13 at 12 57 02 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/fc8a3dcb-b305-40dc-8008-e190090913dc">

It's causing the rest of the preview to be distorted. Ideally the elements would be aligned across all 3, I don't know if that's possible though given the variable nature of the statement description.

2024-06-13 03:02 UTC, james-allan requested changes

2024-06-13 03:02 UTC, james-allan commented on client/settings/payments-and-transactions-section/index.js
> +							text={ `CashApp*${ stripeAccountShortStatementDescriptor } #123456` }
The Cash App preview is slightly incorrect here. It's `CashApp*{company-name}` and because it's not dynamic it won't include the order number either. The Stripe Docs say that the company-name is pulled from [here](https://docs.stripe.com/api/accounts/object#account_object-company-name).

> Every Cash App Pay payment appears on the customer’s bank statement with the CashApp* prefix attached to the merchant name. The merchant name is set to the [`company.name`](https://docs.stripe.com/api/accounts/object#account_object-company-name) field.

So I think this should be 
```suggestion
							text={ `CashApp*${ stripeAccountCompanyName }` }
```

Where `stripeAccountCompanyName` is defined as: 

```js
const stripeAccountCompanyName = data?.account?.company?.name || '';
```

This field is empty on my test account by Stripe's API docs say it should be available for all business types: 


> **Company**
Information about the company or business. This property is available for any business_type. After you create an [Account Link](https://docs.stripe.com/api/account_links) or [Account Session](https://docs.stripe.com/api/account_sessions), this property is only returned for accounts where [controller.requirement_collection](https://docs.stripe.com/api/accounts/object#account_object-controller-requirement_collection) is application, which includes Custom accounts.
<sup>_Ref: https://docs.stripe.com/api/accounts/object#account_object-company_</sup>

2024-06-13 14:25 UTC, wjrosa commented on client/settings/payments-and-transactions-section/index.js
> +							text={ `CashApp*${ stripeAccountShortStatementDescriptor } #123456` }
Thanks, James! I have updated the code to retrieve that information and committed your suggestion 👍

2024-06-13 16:21 UTC, wjrosa commented
> There seems to be an issue with the alignment of the icons:
> 
> <img alt="Screenshot 2024-06-13 at 10 19 35 AM" width="1470" src="https://private-user-images.githubusercontent.com/8490476/339185825-7c8d1070-501d-45a7-afa1-c479ad344c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg4MzcsIm5iZiI6MTcxODI4ODUzNywicGF0aCI6Ii84NDkwNDc2LzMzOTE4NTgyNS03YzhkMTA3MC01MDFkLTQ1YTctYWZhMS1jNDc5YWQzNDRjNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTQyMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWEyM2U0OTY0MmJlYjE5OTI3NzczYjEwNDU2MTUxOWNjYWMyYjUxZDExY2JmYWIwZmUwYjk3YzYzNTE0MzI5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iUEGVdx1Mmeg2Bg4EOfV0szFxt1I2pvgiEmjL6fpFT0">
> On the right is when there are only 2 previews and things look fine. However on the left when there are 3 previews, the icons are unaligned. I spent a bit of time looking into what's causing that, however I wasn't able to find a solution.
> 
> I think it's caused by the previews that overflow to 2 lines in the title.
> 
> <img alt="Screenshot 2024-06-13 at 12 57 02 PM" width="682" src="https://private-user-images.githubusercontent.com/8490476/339194020-fc8a3dcb-b305-40dc-8008-e190090913dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg4MzcsIm5iZiI6MTcxODI4ODUzNywicGF0aCI6Ii84NDkwNDc2LzMzOTE5NDAyMC1mYzhhM2RjYi1iMzA1LTQwZGMtODAwOC1lMTkwMDkwOTEzZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTQyMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAxNmIxZDA2MDIyODA0MmE0ZTAwNmJhYThkOWU0YjExNmI1M2FiY2ZlNmUwYzQ1Mjk5ZTZkZWFhZGIyNDU2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rnP1Iwqiz-lUQiv8YqpxwL93WPgRcy-r8oSHPQ-uAbA">
> It's causing the rest of the preview to be distorted. Ideally the elements would be aligned across all 3, I don't know if that's possible though given the variable nature of the statement description.

You're right, James! I did some CSS adjustments to make it look better. Let me know what you think:
![Screenshot 2024-06-13 at 13 18 40](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/9ced7fa3-8340-43bc-bb44-55012cc17e67)

2024-06-13 16:23 UTC, wjrosa commented
> > There seems to be an issue with the alignment of the icons:
> > <img alt="Screenshot 2024-06-13 at 10 19 35 AM" width="1470" src="https://private-user-images.githubusercontent.com/8490476/339185825-7c8d1070-501d-45a7-afa1-c479ad344c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg4MzcsIm5iZiI6MTcxODI4ODUzNywicGF0aCI6Ii84NDkwNDc2LzMzOTE4NTgyNS03YzhkMTA3MC01MDFkLTQ1YTctYWZhMS1jNDc5YWQzNDRjNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTQyMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWEyM2U0OTY0MmJlYjE5OTI3NzczYjEwNDU2MTUxOWNjYWMyYjUxZDExY2JmYWIwZmUwYjk3YzYzNTE0MzI5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iUEGVdx1Mmeg2Bg4EOfV0szFxt1I2pvgiEmjL6fpFT0">
> > On the right is when there are only 2 previews and things look fine. However on the left when there are 3 previews, the icons are unaligned. I spent a bit of time looking into what's causing that, however I wasn't able to find a solution.
> > I think it's caused by the previews that overflow to 2 lines in the title.
> > <img alt="Screenshot 2024-06-13 at 12 57 02 PM" width="682" src="https://private-user-images.githubusercontent.com/8490476/339194020-fc8a3dcb-b305-40dc-8008-e190090913dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODg4MzcsIm5iZiI6MTcxODI4ODUzNywicGF0aCI6Ii84NDkwNDc2LzMzOTE5NDAyMC1mYzhhM2RjYi1iMzA1LTQwZGMtODAwOC1lMTkwMDkwOTEzZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMTQyMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAxNmIxZDA2MDIyODA0MmE0ZTAwNmJhYThkOWU0YjExNmI1M2FiY2ZlNmUwYzQ1Mjk5ZTZkZWFhZGIyNDU2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rnP1Iwqiz-lUQiv8YqpxwL93WPgRcy-r8oSHPQ-uAbA">
> > It's causing the rest of the preview to be distorted. Ideally the elements would be aligned across all 3, I don't know if that's possible though given the variable nature of the statement description.
> 
> You're right, James! I did some CSS adjustments to make it look better. Let me know what you think: ![Screenshot 2024-06-13 at 13 18 40](https://private-user-images.githubusercontent.com/10187816/339467708-9ced7fa3-8340-43bc-bb44-55012cc17e67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyOTU5ODYsIm5iZiI6MTcxODI5NTY4NiwicGF0aCI6Ii8xMDE4NzgxNi8zMzk0Njc3MDgtOWNlZDdmYTMtODM0MC00M2JjLWJiNDQtNTUwMTJjYzE3ZTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE2MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDZlNWJlOTU2NTVhMjU2M2U3ZTU3ZjIxOTAxMDgzZWMzNjg0NjdkNDE3YzZiMzVlZmNkOGFiZGI0OTU0ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQ7wH5a31bap-CpmTlnSljgoaIpurnoDRO9g8-L1HmU)

Another option would be this (without the `align-items: normal` attribute):
![Screenshot 2024-06-13 at 13 23 09](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/ad730034-e5f6-40bc-abe5-64eb984c33c9)

2024-06-14 02:44 UTC, james-allan approved these changes
Changes look good. Thanks @wjrosa. 

Just noting that I updated the change logs given this PR changed over the course of review and 8.4 has been released. Feel free to tweak the changelog entry if you want. :)

2024-06-14 14:56 UTC, merged