Displaying a notice for risky Cash App transactions
woocommerce/woocommerce-gateway-stripe pull request #3203
Opened 2024-06-12 16:44 UTC by wjrosa

Fixes #

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)

2024-06-13 21:04 UTC, diegocurbelo requested changes
Thanks for working on this @wjrosa!

The message is displayed twice in the Shortcode Checkout

![Screenshot 2024-06-13 at 5 00 58 PM](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/a8330242-dbc5-446e-8a31-58c6b59383af)

Also, can we show the message only when the customer chooses CashApp? and maybe closer or inside the payment selection box instead of a notice at the top?

2024-06-17 14:35 UTC, wjrosa commented
> Thanks for working on this @wjrosa!
> 
> The message is displayed twice in the Shortcode Checkout
> 
> ![Screenshot 2024-06-13 at 5 00 58 PM](https://private-user-images.githubusercontent.com/407542/339535929-a8330242-dbc5-446e-8a31-58c6b59383af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzUxODIsIm5iZiI6MTcxODYzNDg4MiwicGF0aCI6Ii80MDc1NDIvMzM5NTM1OTI5LWE4MzMwMjQyLWRiYzUtNDQ2ZS04YTMxLTU4YzZiNTkzODNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNDM0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGUxMmQ3OWIwYWVlNTNlMzA1NTI0MWNlMmQ5MmM0NWU2MjAxOGU0MzRhNWQ3NGI0MjYzZjFmNTMxMmEzOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oUSI9eYM5GLH-5QLyg1Ssa5XAPmuxJYhMzPY88_FSGw)
> 
> Also, can we show the message only when the customer chooses CashApp? and maybe closer or inside the payment selection box instead of a notice at the top?

Thanks for your review, Diego! I have updated the implementation per your suggestion. It is shown now above the payment selection box and only when Cash App is selected 👍 

Edit: I am still working on the shortcode version 👀 .
Edit 2: Now it is complete and ready for a new review.

2024-06-17 18:59 UTC, wjrosa commented
Some updated preview images:
![Screenshot 2024-06-17 at 15 59 13](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/bd76fd12-9fd9-42af-9466-853f18089065)
![Screenshot 2024-06-17 at 15 59 30](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/0db76250-eafa-4854-9634-3497f1f4938f)

2024-06-17 19:41 UTC, diegocurbelo requested changes
Thanks for the changes @wjrosa!... is working perfectly for both checkouts!

I added a few renaming suggestions to follow the code style used in (most) of the extension.

2024-06-17 19:41 UTC, diegocurbelo commented on client/blocks/upe/upe-deferred-intent-creation/payment-processor.js
> +	const onChange = ( { value, complete } ) => {
Maybe we can use a more self-explanatory name for the callback function, like `onSelectedPaymentMethodChange` or similar.
```suggestion
	const onSelectedPaymentMethodChange = ( { value, complete } ) => {
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/blocks/upe/upe-deferred-intent-creation/payment-processor.js
> +				onChange={ onChange }
Same as above...  `onSelectedPaymentMethodChange` or similar
```suggestion
				onChange={ onSelectedPaymentMethodChange }
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/stripe-utils/cash-app-limit-notice-handler.js
> +export const CashAppNoticeAmountThreshold = 2000;
In other places we use all capital letters with underscores separating words for constants, like:
- https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8a22592a15ec7690e18703a6dc9bcb86593ca4bb/client/blocks/credit-card/constants.js#L2
- https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8a22592a15ec7690e18703a6dc9bcb86593ca4bb/client/blocks/payment-request/constants.js#L1

```suggestion
export const CASHAPP_NOTICE_AMOUNT_THRESHOLD = 2000;
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/stripe-utils/cash-app-limit-notice-handler.js
> +const LimitNoticeClassName = 'wc-block-checkout__payment-method-limit-notice';
```suggestion
const LIMIT_NOTICE_CLASSNAME = 'wc-block-checkout__payment-method-limit-notice';
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/stripe-utils/cash-app-limit-notice-handler.js
> +	if ( cartAmount <= CashAppNoticeAmountThreshold ) {
```suggestion
	if ( cartAmount <= CASHAPP_NOTICE_AMOUNT_THRESHOLD ) {
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/stripe-utils/cash-app-limit-notice-handler.js
> +	const limitNotice = document.querySelector( '.' + LimitNoticeClassName );
```suggestion
	const limitNotice = document.querySelector( '.' + LIMIT_NOTICE_CLASSNAME );
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/stripe-utils/cash-app-limit-notice-handler.js
> +CashAppLimitNotice.setAttribute( 'data-testid', 'cash-app-limit-notice' );
In other places we use camelCase for variables (regardless if they were defined with `var`, `const` or `let`).
```suggestion
export const cashAppLimitNotice = document.createElement( 'div' );
cashAppLimitNotice.classList.add( 'woocommerce-info', LIMIT_NOTICE_CLASSNAME );
cashAppLimitNotice.textContent = __(
	'Please note that, depending on your account and transaction history, Cash App Pay may reject your transaction due to its amount.'
);
cashAppLimitNotice.setAttribute( 'data-testid', 'cash-app-limit-notice' );
```

2024-06-17 19:41 UTC, diegocurbelo commented on client/stripe-utils/cash-app-limit-notice-handler.js
> +	}
```suggestion
	if ( appendToElement ) {
		wrapperElement.appendChild( cashAppLimitNotice );
	} else {
		wrapperElement.insertBefore(
			cashAppLimitNotice,
			wrapperElement.firstChild
		);
	}
```

2024-06-17 21:54 UTC, wjrosa commented
Cool, @diegocurbelo ! I have included all your commit suggestions and fixed some issues with them. I didn't pay attention to all those standards, but I got them now 🙌

2024-06-18 20:04 UTC, diegocurbelo approved these changes
Thanks for fixing those; we should have better linting checks... it might be a nice project for the next hack week.

2024-06-18 21:03 UTC, merged