Improving webhook related labels
woocommerce/woocommerce-gateway-stripe pull request #3288
Opened 2024-07-18 21:05 UTC by wjrosa

Fixes #

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

2024-07-22 01:09 UTC, james-allan requested changes
@wjrosa I've left some comments. Let me know what you think about how we should tackle this.

I reviewed the other changes too. The old message on how to configure webhooks is below. 

<img width="768" alt="Screenshot 2024-07-22 at 10 44 41 AM" src="https://github.com/user-attachments/assets/9908fbfb-6ddb-4f58-93f2-caa379ce1088">

The **Configure connection** button is updated and the steps on how to configure the webhooks is also updated: 

<img width="776" alt="Screenshot 2024-07-22 at 10 47 19 AM" src="https://github.com/user-attachments/assets/a5a4117b-0e73-4185-800d-dad157ff27c2">

2024-07-22 01:09 UTC, james-allan commented on client/components/webhook-description/index.js
> +		message?.includes( 'The most recent ' ) && isWarningMessage === false;
I hadn't picked this up in the previous PR but using the content of a message isn't a robust way of obtaining context like this. The string is translated on the server and so whether it includes "The most recent" or "Warning: " won't consistently work on international/translated sites.

To color this notice and determine what should be displayed based on whether the webhook message is successful or an error we really need to introduce a codified status. I don't know how we should move forward here. I suspect reworking this to introduce a status like that isn't a small change.

2024-07-22 01:09 UTC, james-allan commented on client/components/webhook-information/index.js
> +					'Click the {{webhookUrl/}} button to {{settingsLink}}configure a webhook{{/settingsLink}}. This will complete your Stripe account connection process.',
Given this isn't a URL anymore we should change this placeholder name. 

```suggestion
					'Click the {{configureButtonText/}} button to {{settingsLink}}configure a webhook{{/settingsLink}}. This will complete your Stripe account connection process.',
```

2024-07-22 01:09 UTC, james-allan commented on client/components/webhook-information/index.js
>  					webhookUrl: (
```suggestion
					configureButtonText: (
```

2024-07-23 16:14 UTC, wjrosa commented on client/components/webhook-description/index.js
> +		message?.includes( 'The most recent ' ) && isWarningMessage === false;
You're right, James! The previous change was simpler, so I guess it was okay to do. But here it got more complex, so a code would be better. I made the change now, it was not a big deal at all 👍

2024-07-26 05:06 UTC, james-allan approved these changes
Changes look good. I tested all 4 webhooks statuses and confirmed they are displayed correctly. 

#### `4` - error 
<img width="763" alt="Screenshot 2024-07-26 at 2 59 05 PM" src="https://github.com/user-attachments/assets/fd3b5e65-891e-443c-b052-83bcabf56c05">

#### `3` - error after prior success

<img width="759" alt="Screenshot 2024-07-26 at 2 58 40 PM" src="https://github.com/user-attachments/assets/57d498d4-698b-4935-8f35-211da44bca8d">

#### `2` - no webhook yet
<img width="761" alt="Screenshot 2024-07-26 at 2 58 13 PM" src="https://github.com/user-attachments/assets/43eda212-b9bb-4944-8f5f-e5aa432373ec">

#### `1` - success
<img width="767" alt="Screenshot 2024-07-26 at 2 57 55 PM" src="https://github.com/user-attachments/assets/707cd17f-fdbe-4823-91cd-0c9e3738ffac">

#### The new configure connection button + webhook configuration guide. 

<img width="730" alt="Screenshot 2024-07-26 at 3 05 34 PM" src="https://github.com/user-attachments/assets/da07c00e-e447-46b6-9bf7-0c90a9fb9be9">


👍

2024-07-26 12:33 UTC, merged