Introducing the Re-Connect Promotional Surface
woocommerce/woocommerce-gateway-stripe pull request #3322
Opened 2024-07-30 14:43 UTC by wjrosa

Fixes #3278

## Changes proposed in this Pull Request:

## Testing instructions

---

-   [ ] Covered with tests (or have a good reason not to test in description ☝️)
-   [ ] Added changelog entry **in both** `changelog.txt` and `readme.txt` (or does not apply)
-   [ ] Tested on mobile (or does not apply)

**Post merge**

-   [ ] Added testing instructions to the [Release Testing Instructions wiki page](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Release-Testing-Instructions) (or does not apply)
-   [ ] Added the [needs docs label](https://github.com/woocommerce/woocommerce-gateway-stripe/labels?q=docs) (or does not apply)
-   [ ] Included this PR in the Release Thread scope (or does not apply)

2024-07-31 07:19 UTC, Mayisha requested changes
Thanks @wjrosa for implementing this. I have tested the PR and it works as described.

- When my site has not been re-connected, I see the re-auth promotional banner.

<img width="780" alt="Screenshot 2024-07-31 at 12 25 46 PM" src="https://github.com/user-attachments/assets/078e3993-22a8-4667-87a2-fc2b5deb03de">

- The account connection modal is displayed when I click the `Configure connection` button.


<img width="621" alt="Screenshot 2024-07-31 at 12 26 10 PM" src="https://github.com/user-attachments/assets/c5dd3072-bea6-47ca-b829-4311041fbaa3">

I have a feedback about avoiding JQuery with React. 

I also have a minor suggestion. This is not a blocker to this PR but I think it could be a good enhancement. We are showing the promotional banner on the `Settings` tab of the Stripe settings page. When a merchant comes to the Stripe settings page, they first land on the `Payment methods` tab and unless they go to the `Settings` tab, they won't see the banner or know about this. I think it would be more effective if we display the banner on both of the tabs.

2024-07-31 07:19 UTC, Mayisha commented on client/settings/payment-settings/promotional-banner-section.js
> +		jQuery( '#btn-configure-connection' ).trigger( 'click' );
What are your thoughts on handling the button click by sending necessary props from `client/settings/payment-settings/index.js` to this component? We should avoid mixing React and jQuery unless this is the only possible solution.

2024-08-05 15:40 UTC, wjrosa commented on client/settings/payment-settings/promotional-banner-section.js
> +		jQuery( '#btn-configure-connection' ).trigger( 'click' );
Oh ok! I just replaced it and used the props instead 👍

2024-08-05 18:56 UTC, diegocurbelo commented
Hey @wjrosa!

How about changing the button to start the OAuth flow (by just using the oauthURL we use in the modal) without the need to open the modal... this would also make showing the banner in both the `Payment methods` and the `Settings` tabs easier.

2024-08-05 21:09 UTC, wjrosa commented
Thanks for the suggestions, @diegocurbelo ! I made the changes now. I sent you additional context over Slack, let me know if you want me to revert the last commit.

Also, with this change, it is not possible to test the connection flow over localhost. Stripe returns an empty URL for both live and test in this case.

2024-08-06 04:56 UTC, diegocurbelo commented
> Also, with this change, it is not possible to test the connection flow over localhost. Stripe returns an empty URL for both live and test in this case.

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3337 fixes that

2024-08-06 19:37 UTC, diegocurbelo requested changes
Thanks for working on this @wjrosa!

The code looks good, and it tests well. 
I added a couple of suggested text changes.

2024-08-06 19:37 UTC, diegocurbelo commented on client/settings/payment-settings/promotional-banner-section.js
> +							'Re-authenticate your Stripe account using the new flow by clicking the "Configure connection" button and make your store safer.',
```suggestion
							'Re-connect your Stripe account using the new authentication flow by clicking the "Re-authenticate" button and make your store safer.',
```

2024-08-06 19:37 UTC, diegocurbelo commented on client/settings/payment-settings/promotional-banner-section.js
> +					) }
```suggestion
					{ __( 'Re-authenticate', 'woocommerce-gateway-stripe' ) }
```

2024-08-06 20:02 UTC, merged