Fix Stripe disable modal text
woocommerce/woocommerce-gateway-stripe pull request #3526
Opened 2024-10-21 09:59 UTC by Mayisha

## Changes proposed in this Pull Request:

## Testing instructions
<img width="653" alt="Screenshot 2024-10-21 at 2 34 04 PM" src="https://github.com/user-attachments/assets/59968fa0-f94c-44ef-bab3-8f327afcffe2">
<img width="653" alt="Screenshot 2024-10-21 at 3 30 19 PM" src="https://github.com/user-attachments/assets/164914c6-d274-4297-95fc-eac007bb29c8">

2024-10-23 16:22 UTC, annemirasol requested changes
Found this odd behavior:

1. Check out this branch.
2. Go to Payment Methods and enable Link.
3. Refresh the page.
4. Notice that Link is unchecked.
5. Checkout `develop` and refresh the page.
6. Notice that Link is checked.

2024-10-24 11:37 UTC, Mayisha commented on client/blocks/express-checkout/index.js
> +	gatewayId: 'stripe',
The changes in this file are not relevant to the modal text, also it does not visibly do anything. I just piggybacked these little changes here. These attributes were missing from the object.

2024-10-24 11:40 UTC, Mayisha commented
> Found this odd behavior

Thanks @annemirasol. That's a good finding which I totally missed.

I moved the filtering to the modal specific file in the frontend [93a647a](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3526/commits/93a647afcb11e70e21a4ead6218feb31ed90b3d7), so it should not create regression anywhere else now

2024-10-24 15:12 UTC, annemirasol approved these changes
Thanks for fixing ✨ Code looks good!

✅ I tested turning off the Stripe plugin with different methods enabled, and everything looks good.
✅ Smoke-tested express payment purchases

2024-10-24 16:41 UTC, merged

2024-10-24 18:13 UTC, annemirasol commented
@Mayisha Forgot to mention I noticed the PR doesn't have changelog/readme entries. Maybe it can piggyback on your next PR? Or perhaps not even necessary if we're switching to the Jetpack changelogger soon. FYI anyways.

2024-10-25 04:00 UTC, Mayisha commented
Thank @annemirasol. I prepared the changelog commit locally but forgot to push the commit 😳