Improve webhook status related messages on the settings page.
woocommerce/woocommerce-gateway-stripe pull request #3681
Opened 2024-12-26 18:38 UTC by Mayisha

Fixes #3342

## Changes proposed in this Pull Request:

## Testing instructions

2024-12-31 15:16 UTC, Mayisha commented on includes/class-wc-stripe-webhook-state.php
> +			return( __( 'The webhook secret is not set in the store. Please configure the webhooks', 'woocommerce-gateway-stripe' ) );
Not sure if this extra line is actually adding any better information 🤔

2025-01-02 16:05 UTC, annemirasol commented on includes/class-wc-stripe-webhook-state.php
> +			return( __( 'The webhook secret is not set in the store. Please configure the webhooks', 'woocommerce-gateway-stripe' ) );
I like that we're adding an action item 👍

2025-01-02 16:16 UTC, annemirasol approved these changes
Added some suggestions in comments.

LGTM ✨ 🚢, was able to verify the new error message, and that re-configuring removes the duplicate webhook.

2025-01-02 16:16 UTC, annemirasol commented on includes/class-wc-stripe-webhook-handler.php
> +		$number_of_duplicate_webhooks = count( $webhooks );
Shouldn't this start at `0` since we only want to count it if the webhook URL matches the site?

Nit: Maybe `$number_of_webhooks` instead of `$number_of_duplicate_webhooks`?

2025-01-02 16:16 UTC, annemirasol commented on includes/class-wc-stripe-webhook-state.php
> +			return( __( 'Multiple webhooks are created for this site. Please remove the duplicate webhooks or re-configure the webhooks', 'woocommerce-gateway-stripe' ) );
Nit: `exist` instead of `are created`? The latter gave me the impression that our side created multiple webhooks for them as a result of the error.

2025-01-02 18:55 UTC, annemirasol commented
Sorry, caught this late in the logs:

```
[02-Jan-2025 18:54:18 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php on line 151
```

2025-01-02 18:57 UTC, annemirasol requested changes
Sorry, caught this late in the logs:

```
[02-Jan-2025 18:54:18 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php on line 151
```

2025-01-03 13:54 UTC, Mayisha commented on includes/class-wc-stripe-webhook-handler.php
> +		$number_of_duplicate_webhooks = count( $webhooks );
I don't remember when I changed it to `count` from `0`. It makes the logic totally wrong here 😳

2025-01-03 15:39 UTC, Mayisha commented on includes/class-wc-stripe-webhook-state.php
> +			return( __( 'Multiple webhooks are created for this site. Please remove the duplicate webhooks or re-configure the webhooks', 'woocommerce-gateway-stripe' ) );
Changed in [a489c7e](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3681/commits/a489c7ed6d39538cbbe3a2a08176bcc771314eba)

2025-01-03 15:41 UTC, Mayisha commented on includes/class-wc-stripe-webhook-handler.php
> +		$number_of_duplicate_webhooks = count( $webhooks );
Fixed this in [d26e5be](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3681/commits/d26e5be5aac8102f94a2a459637a4f4cd6b6a221). 

> Sorry, caught this late in the logs:
```
[02-Jan-2025 18:54:18 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-webhook-handler.php on line 151
```

The change should also fix the above error as we don't have the usage of `count` now.

2025-01-03 19:34 UTC, annemirasol approved these changes
Works great, code LGTM ✨ 🚢 Thanks for taking care of this!

2025-01-06 06:00 UTC, merged