Fix ECE button displayed on synced subscription variations
woocommerce/woocommerce-gateway-stripe pull request #3686
Opened 2024-12-30 14:12 UTC by Mayisha

Fixes #3607 

## Changes proposed in this Pull Request:
ECE buttons should be hidden if the subscription is synchronized. In variable subscriptions with synced and non-synced variations, ECE button still appears when switched to a synced variation. This PR fixes the issue by checking if `getSelectedProductData` response has an error. 

## Testing instructions

- Create a variable subscription product with 2 variations (Blue and Red) and a sign up free.
- Make the Blue variation synchronized (i.e on 10th day).
- Enable the ECE feature flag.
- As a shopper go to the product page.
- Notice that, in `develop` branch the ECE button is displayed for both variations.
- Confirm that in this branch the ECE button is displayed only for the unsynced variation (Red).

2024-12-30 17:04 UTC, annemirasol requested changes
@Mayisha TIL synced subscriptions! 🙌 

1. During testing, I found a flow that still displayed the ECE buttons even when synced variation is selected:
   1. Go to product page.
   2. Select Blue (synced).
   4. Notice ECE buttons disappear.
   5. Click "Sign up now" button.
   6. Notice page is reloaded, Blue is selected, and ECE buttons are visible.

2. Also, I don't quite get the reason -- why are we hiding ECE for synced subs? If "Due Today" is not 0.00 and if we allow payment via other payment methods, shouldn't we also allow payment via ECE?

2025-01-01 09:42 UTC, Mayisha commented
Thanks @annemirasol for the feedback.

> During testing, I found a flow that still displayed the ECE buttons even when synced variation is selected:

Good finding 👍 I totally missed this issue. I have fixed it in [e680de2](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3686/commits/e680de29979271ac2fec0bdf96658bda8aaf84c5). The `validVariationSelected` is used in PRB also to check if the selected product is supported for PRB payments. We had this attribute set for ECE also in the backend but missed checking it on the frontend.

> Also, I don't quite get the reason -- why are we hiding ECE for synced subs? If "Due Today" is not 0.00 and if we allow payment via other payment methods, shouldn't we also allow payment via ECE?

We are hiding ECE for synced subs only on the product page. According to the `is_invalid_subscription_product` [function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-express-checkout-helper.php#L423-L439), for synced subs

``` this limitation only applies to the product page as we cannot calculate totals correctly ```

According to the function if you select `Never (charge the full recurring amount at sign-up)` in the subscription settings ( WooCommerce > Settings > Subscriptions), the ECE button should be present.

<img width="845" alt="Screenshot 2025-01-01 at 3 39 05 PM" src="https://github.com/user-attachments/assets/83f1c8cb-b17a-469b-986b-0d3ac5cd4407" />

2025-01-02 18:29 UTC, annemirasol commented
> We are hiding ECE for synced subs only on the product page. According to the is_invalid_subscription_product [function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-express-checkout-helper.php#L423-L439), for synced subs
>
> this limitation only applies to the product page as we cannot calculate totals correctly


@Mayisha I don't see the ECE buttons in the cart and checkout pages, when a synced sub is in the cart. Is this expected? 

(I can see them with the non-synced sub.)


> According to the function if you select Never (charge the full recurring amount at sign-up) in the subscription settings ( WooCommerce > Settings > Subscriptions), the ECE button should be present.

Verified 👍 I see them if we're charging full amount.

2025-01-03 16:38 UTC, Mayisha commented
> @Mayisha I don't see the ECE buttons in the cart and checkout pages, when a synced sub is in the cart. Is this expected?

Upon checking the `is_invalid_subscription_product` function again, this seems expected as per [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L653) and [this condition](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L696-L697). 

> this limitation only applies to the product page as we cannot calculate totals correctly

This statement is actually for the virtual synced subscription only as per [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L654) and [this condition](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L684).
Apologies for the confusion. 

Note: I have referenced the lines from the function in the payment request class where the function was originally added.

2025-01-03 19:26 UTC, annemirasol commented
> This statement is actually for the virtual synced subscription only as per [this comment](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L654) and [this condition](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L684).

I see, thanks for clarifying that!


Flow:
1. Go to product page.
2. Select Blue, ECE gets hidden.
3. Select Red, ECE remains hidden.

Maybe a `wcStripeECE.show();` needs to be in the `else` clause of `if (response.error)`?

2025-01-31 14:22 UTC, Mayisha commented
> Maybe a wcStripeECE.show(); needs to be in the else clause of if (response.error)?

Fixed in [a7e378f](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3686/commits/a7e378f82720a6e213dab8d2a7b9c3a2964cd2ba). 👀

2025-01-31 19:27 UTC, annemirasol approved these changes
LGTM, tests out as described!

2025-02-03 16:47 UTC, merged